/** Only application-owned errors. Provider responses, tool output and file contents are opaque. */
export const appErrors = {
  '任务不存在': 'Task not found',
  '项目不存在': 'Project not found',
  '不允许的请求来源': 'Request origin is not allowed',
  '请先在设置中配置供应商与模型，再为任务选择模型。': 'Configure a provider and model in Settings, then select a model for this task.',
  '该供应商尚未设置 API Key': 'This provider has no API key',
  '请先停止该项目的任务再创建 worktree': 'Stop this project’s tasks before creating a worktree',
  '请通过附件选择器添加文件': 'Add files using the attachment picker',
  '请先从回收站恢复任务': 'Restore the task from the recycle bin first',
  '任务正在运行，请选择排队、引导或停止': 'The task is running. Queue a message, steer it, or stop it.',
  '请先停止此仓库的活动任务再执行此 Git 操作': 'Stop active tasks in this repository before performing this Git operation',
  '请先停止此项目的活动任务再执行此 Git 操作': 'Stop active tasks in this project before performing this Git operation',
  '请先停止该项目的运行任务再修改信任设置': 'Stop this project’s tasks before changing trust settings',
  '该路径不是当前仓库的 worktree': 'This path is not a worktree of the current repository',
  '任务运行、等待审批或位于回收站时不能标记已审阅': 'A running task, a task awaiting approval, or a recycled task cannot be marked reviewed',
  '请先停止任务再移入回收站': 'Stop the task before moving it to the recycle bin',
  '请停止任务后修改运行配置': 'Stop the task before changing its run configuration',
  '此模型未允许该思考程度，请在模型设置中修改': 'This reasoning effort is not enabled. Change it in model settings.',
  '只能永久删除回收站中的空闲任务': 'Only idle tasks in the recycle bin can be permanently deleted',
  '请选择模型': 'Select a model',
  '请等待任务空闲再压缩上下文': 'Wait for the task to finish before compacting context',
  '请等待任务空闲再分叉': 'Wait for the task to finish before forking',
  'Pi 未返回分叉会话': 'Pi did not return a forked session',
  '该审批已结束': 'This approval has ended',
  '请选择有效选项': 'Select a valid option',
  '请选择普通文件': 'Select a regular file',
  '请先停止运行任务再保存设置': 'Stop running tasks before saving settings',
  '请先停止该模型正在运行的任务，再更新 API Key': 'Stop tasks using this model before updating its API key',
  '请先停止运行任务再创建 Skill': 'Stop running tasks before creating a skill',
  '请先停止运行任务再更新 MCP 密钥': 'Stop running tasks before updating MCP secrets',
  '请先保存 MCP 配置': 'Save the MCP configuration first',
  '请先停止此任务再重新连接工具': 'Stop this task before reconnecting tools',
  '请填写自动化名称和任务描述': 'Enter an automation name and task description',
  '自动化不存在': 'Automation not found',
  '此 worktree 仍有运行任务': 'This worktree still has running tasks',
  '请先停止此项目的活动任务再恢复文件': 'Stop this project’s active tasks before restoring files',
  '操作已取消': 'Operation canceled',
  '请先停止此项目的活动任务再提交': 'Stop this project’s active tasks before committing',
  '请先停止此项目的活动任务再应用改动': 'Stop this project’s active tasks before applying changes',
  '当前任务不在 Worktree 中': 'The current task is not in a worktree',
  '请等待运行任务结束再刷新资源；改动将在下次任务运行时生效': 'Wait for running tasks to finish before refreshing resources; changes apply on the next run',
  '资源不存在': 'Resource not found',
  '该资源不是可读取的小型文本文件，请在文件位置中查看': 'This resource is not a readable small text file. Open its file location.',
  '无法打开编辑器，请在设置中选择系统默认应用': 'Cannot open the editor. Select the system default app in Settings.',
  '终端入口不存在': 'Terminal entry not found',
  '任务存储标识无效': 'Invalid task storage identifier',
  '请选择文件': 'Select a file',
  '缺少有效差异块': 'No valid diff hunk was provided',
  '请输入提交信息': 'Enter a commit message',
  '请先解决冲突': 'Resolve conflicts first',
  '请选择本次提交的暂存文件': 'Select staged files for this commit',
  '合并或变基期间请使用继续操作': 'Use Continue during a merge or rebase',
  '所选文件已不在暂存区，请刷新后重试': 'The selected files are no longer staged. Refresh and retry.',
  '所选文件没有暂存改动': 'The selected files have no staged changes',
  '工作区有未提交内容，请先提交或自行处理后切换分支': 'The workspace has uncommitted changes. Resolve them before switching branches.',
  '所选远端分支不存在，请先获取并刷新': 'The selected remote branch does not exist. Fetch and refresh first.',
  '请输入远端跟踪分支': 'Enter a remote tracking branch',
  '请选择已有远端': 'Select an existing remote',
  '分离 HEAD 状态不能直接推送': 'Cannot push directly from a detached HEAD',
  '请选择目标分支': 'Select a target branch',
  '没有可继续或中止的合并／变基': 'There is no merge or rebase to continue or abort',
  '请选择完整 worktree 路径': 'Select the full worktree path',
  '只允许清理其他由 Pi 管理的 worktree': 'Only other Pi-managed worktrees can be cleaned up',
  'Worktree 有未提交内容，不能清理': 'This worktree has uncommitted changes and cannot be cleaned up',
  'Worktree 没有可应用的改动': 'This worktree has no changes to apply',
  '不支持的 Git 操作': 'Unsupported Git operation',
  '密钥存储已损坏': 'The secret store is corrupted',
  '系统加密存储不可用': 'System encrypted storage is unavailable',
  '系统加密存储不可用，未保存密钥': 'System encrypted storage is unavailable; the secret was not saved',
  '未找到 Git Bash，请先安装 Git for Windows': 'Git Bash was not found. Install Git for Windows first.',
  '终端已关闭': 'The terminal is closed',
  '终端不存在': 'Terminal not found',
  '文件超过 10 MB，请在外部编辑器中打开': 'This file exceeds 10 MB. Open it in an external editor.',
  '此文件仅支持在外部编辑器中修改': 'This file can only be changed in an external editor',
  '文件已被其他程序修改，请重新加载并合并后保存': 'Another program changed this file. Reload and merge before saving.',
  '保存期间文件发生变化，未覆盖原文件': 'The file changed while saving; the original was not overwritten',
  '请先打开一个 HTTP(S) 网站': 'Open an HTTP(S) website first',
  '下载记录不存在': 'Download record not found',
  '扩展路径不是普通文件': 'The extension path is not a regular file',
  '路径超出项目目录': 'The path is outside the project directory',
  '链接目标超出项目目录': 'The link target is outside the project directory',
  '无法确认项目路径': 'Cannot verify the project path',
  '搜索已停止': 'Search stopped',
  '搜索已过期，请重新搜索': 'Search expired. Search again.',
  '同时搜索的任务过多，请稍后重试': 'Too many concurrent searches. Try again shortly.',
  '搜索条件已改变，请重新搜索': 'Search criteria changed. Search again.',
  '上一页仍在搜索，请稍后重试': 'The previous page is still searching. Try again shortly.',
  '搜索页已失效，请重新搜索': 'This search page expired. Search again.',
  '请输入有效网址；空格请使用 %20': 'Enter a valid URL; encode spaces as %20',
  '仅支持 HTTP 或 HTTPS 网址': 'Only HTTP or HTTPS URLs are supported',
  '请输入不含用户名和密码的有效 HTTP 或 HTTPS 网址': 'Enter a valid HTTP or HTTPS URL without a username or password',
  '无法计算下一次日历运行时间': 'Cannot calculate the next scheduled run',
  '内置模型目录为空，请使用自定义接口': 'The built-in model catalog is empty. Use a custom endpoint.',
  '此内置模型不能自动转换，请新建自定义接口': 'This built-in model cannot be converted automatically. Create a custom endpoint.',
  '请填写模型的显示名称': 'Enter a display name for the model',
  '请填写接口服务提供的模型 ID': 'Enter the model ID provided by the endpoint',
  '请至少选择一个允许的思考程度': 'Select at least one allowed reasoning effort',
  '上下文窗口需为 1,024–10,000,000 之间的整数': 'The context window must be an integer between 1,024 and 10,000,000',
  '最大输出 Token 需为 256–1,000,000 之间的整数': 'Maximum output tokens must be an integer between 256 and 1,000,000',
  '请填写有效的 Base URL': 'Enter a valid Base URL',
  'Base URL 必须是 HTTP(S) 地址，密钥请填入 API Key': 'Base URL must use HTTP(S). Enter credentials in API Key.',
  '内置模型目录尚未加载，请重试或选择自定义接口': 'The built-in model catalog has not loaded. Retry or use a custom endpoint.',
  '当前模型不在该供应商的内置目录中，请重新选择或改用自定义接口': 'The current model is not in this provider’s catalog. Choose another model or a custom endpoint.',
  '所选思考程度不在此内置模型支持的范围内': 'The selected reasoning effort is not supported by this built-in model',
  '请填写服务名称': 'Enter a server name',
  '请填写启动命令': 'Enter a launch command',
  'MCP URL 必须使用 HTTP(S)': 'The MCP URL must use HTTP(S)',
  '请填写完整的 HTTP(S) 端点地址': 'Enter a complete HTTP(S) endpoint URL',
  '加密环境变量需为字符串值的 JSON 对象': 'Encrypted environment variables must be a JSON object with string values',
} as const;
