/** Only application-owned errors. Provider responses, tool output and file contents are opaque. */
export const appErrors = {
  '任务不存在': 'Task not found',
  '项目不存在': 'Project not found',
  '不允许的请求来源': 'Request origin is not allowed',
  '请先在设置中配置模型提供商与模型，再为任务选择模型。': 'Configure a model provider and model in Settings, then select a model for this task.',
  '该模型提供商尚未设置 API Key': 'This model provider has no API key',
  '模型提供商已不存在，请重新打开设置后重试。': 'This model provider no longer exists. Reopen settings and retry.',
  '请填写提供商的显示名称': 'Enter a display name for the provider',
  '内置供应商已不存在，请重新选择': 'The built-in provider no longer exists. Choose another one.',
  '所属提供商已不存在，请重新选择': 'Its provider no longer exists. Choose another provider.',
  '请填写接口服务地址': 'Enter the endpoint address',
  '自定义提供商必须填写 Base URL': 'A custom provider must set a Base URL',
  'Base URL 必须使用 HTTP(S)': 'Base URL must use HTTP(S)',
  '请先停止该项目的任务再创建 worktree': 'Stop this project’s tasks before creating a worktree',
  '请通过附件选择器添加文件': 'Add files using the attachment picker',
  '请先从回收站恢复任务': 'Restore the task from the recycle bin first',
  '任务正在运行，请选择排队、引导或停止': 'The task is running. Queue a message, steer it, or stop it.',
  '请先停止此仓库的活动任务再执行此 Git 操作': 'Stop active tasks in this repository before performing this Git operation',
  '请先停止此项目的活动任务再执行此 Git 操作': 'Stop active tasks in this project before performing this Git operation',
  '请先停止该项目的运行任务再修改信任设置': 'Stop this project’s tasks before changing trust settings',
  '该路径不是当前仓库的 worktree': 'This path is not a worktree of the current repository',
  '任务运行、等待审批或位于回收站时不能标记已审阅': 'A running task, a task awaiting approval, or a recycled task cannot be marked reviewed',
  '请先停止任务再移入回收站': 'Stop the task before moving it to the recycle bin',
  '请停止任务后修改运行配置': 'Stop the task before changing its run configuration',
  '此模型未允许该思考程度，请在模型设置中修改': 'This reasoning effort is not enabled. Change it in model settings.',
  '请先停止任务再删除': 'Stop the task before deleting it',
  '请选择模型': 'Select a model',
  '请等待任务空闲再压缩上下文': 'Wait for the task to finish before compacting context',
  '请等待任务空闲再分叉': 'Wait for the task to finish before forking',
  'Pi 未返回分叉会话': 'Pi did not return a forked session',
  '该审批已结束': 'This approval has ended',
  '请选择有效选项': 'Select a valid option',
  '请选择普通文件': 'Select a regular file',
  '请先停止运行任务再保存设置': 'Stop running tasks before saving settings',
  '请先停止该模型正在运行的任务，再更新 API Key': 'Stop tasks using this model before updating its API key',
  '请先停止运行任务再创建 Skill': 'Stop running tasks before creating a skill',
  '请先停止运行任务再更新 MCP 密钥': 'Stop running tasks before updating MCP secrets',
  '请先保存 MCP 配置': 'Save the MCP configuration first',
  '请先停止此任务再重新连接工具': 'Stop this task before reconnecting tools',
  '请填写自动化名称和任务描述': 'Enter an automation name and task description',
  '自动化不存在': 'Automation not found',
  '此 worktree 仍有运行任务': 'This worktree still has running tasks',
  '请先停止此项目的活动任务再恢复文件': 'Stop this project’s active tasks before restoring files',
  '操作已取消': 'Operation canceled',
  '请先停止此项目的活动任务再提交': 'Stop this project’s active tasks before committing',
  '请先停止此项目的活动任务再应用改动': 'Stop this project’s active tasks before applying changes',
  '当前任务不在 Worktree 中': 'The current task is not in a worktree',
  '请等待运行任务结束再刷新资源；改动将在下次任务运行时生效': 'Wait for running tasks to finish before refreshing resources; changes apply on the next run',
  '资源不存在': 'Resource not found',
  '该资源不是可读取的小型文本文件，请在文件位置中查看': 'This resource is not a readable small text file. Open its file location.',
  '无法打开编辑器，请在设置中选择系统默认应用': 'Cannot open the editor. Select the system default app in Settings.',
  '终端入口不存在': 'Terminal entry not found',
  '任务存储标识无效': 'Invalid task storage identifier',
  '请选择文件': 'Select a file',
  '缺少有效差异块': 'No valid diff hunk was provided',
  '请输入提交信息': 'Enter a commit message',
  '请先解决冲突': 'Resolve conflicts first',
  '请选择本次提交的暂存文件': 'Select staged files for this commit',
  '合并或变基期间请使用继续操作': 'Use Continue during a merge or rebase',
  '所选文件已不在暂存区，请刷新后重试': 'The selected files are no longer staged. Refresh and retry.',
  '所选文件没有暂存改动': 'The selected files have no staged changes',
  '工作区有未提交内容，请先提交或自行处理后切换分支': 'The workspace has uncommitted changes. Resolve them before switching branches.',
  '所选远端分支不存在，请先获取并刷新': 'The selected remote branch does not exist. Fetch and refresh first.',
  '请输入远端跟踪分支': 'Enter a remote tracking branch',
  '请选择已有远端': 'Select an existing remote',
  '分离 HEAD 状态不能直接推送': 'Cannot push directly from a detached HEAD',
  '请选择目标分支': 'Select a target branch',
  '没有可继续或中止的合并／变基': 'There is no merge or rebase to continue or abort',
  '请选择完整 worktree 路径': 'Select the full worktree path',
  '只允许清理其他由 Pi 管理的 worktree': 'Only other Pi-managed worktrees can be cleaned up',
  'Worktree 有未提交内容，不能清理': 'This worktree has uncommitted changes and cannot be cleaned up',
  'Worktree 没有可应用的改动': 'This worktree has no changes to apply',
  '不支持的 Git 操作': 'Unsupported Git operation',
  '密钥存储已损坏': 'The secret store is corrupted',
  '系统加密存储不可用': 'System encrypted storage is unavailable',
  '系统加密存储不可用，未保存密钥': 'System encrypted storage is unavailable; the secret was not saved',
  '未找到 Git Bash，请先安装 Git for Windows': 'Git Bash was not found. Install Git for Windows first.',
  '终端已关闭': 'The terminal is closed',
  '终端不存在': 'Terminal not found',
  '文件超过 10 MB，请在外部编辑器中打开': 'This file exceeds 10 MB. Open it in an external editor.',
  '此文件仅支持在外部编辑器中修改': 'This file can only be changed in an external editor',
  '文件已被其他程序修改，请重新加载并合并后保存': 'Another program changed this file. Reload and merge before saving.',
  '保存期间文件发生变化，未覆盖原文件': 'The file changed while saving; the original was not overwritten',
  '请先打开一个 HTTP(S) 网站': 'Open an HTTP(S) website first',
  '下载记录不存在': 'Download record not found',
  '扩展路径不是普通文件': 'The extension path is not a regular file',
  '路径超出项目目录': 'The path is outside the project directory',
  '链接目标超出项目目录': 'The link target is outside the project directory',
  '无法确认项目路径': 'Cannot verify the project path',
  '搜索已停止': 'Search stopped',
  '搜索已过期，请重新搜索': 'Search expired. Search again.',
  '同时搜索的任务过多，请稍后重试': 'Too many concurrent searches. Try again shortly.',
  '搜索条件已改变，请重新搜索': 'Search criteria changed. Search again.',
  '上一页仍在搜索，请稍后重试': 'The previous page is still searching. Try again shortly.',
  '搜索页已失效，请重新搜索': 'This search page expired. Search again.',
  '请输入有效网址；空格请使用 %20': 'Enter a valid URL; encode spaces as %20',
  '仅支持 HTTP 或 HTTPS 网址': 'Only HTTP or HTTPS URLs are supported',
  '请输入不含用户名和密码的有效 HTTP 或 HTTPS 网址': 'Enter a valid HTTP or HTTPS URL without a username or password',
  '无法计算下一次日历运行时间': 'Cannot calculate the next scheduled run',
  '内置模型目录尚未加载，请重试或改用自定义提供商': 'The built-in model catalog has not loaded. Retry or use a custom provider.',
  '当前模型不在该提供商的内置目录中，请重新选择或改用自定义提供商': 'The current model is not in this provider’s catalog. Choose another model or a custom provider.',
  '请填写模型的显示名称': 'Enter a display name for the model',
  '请填写接口服务提供的模型 ID': 'Enter the model ID provided by the endpoint',
  '请至少选择一个允许的思考程度': 'Select at least one allowed reasoning effort',
  '上下文窗口需为 1,024–10,000,000 之间的整数': 'The context window must be an integer between 1,024 and 10,000,000',
  '最大输出 Token 需为 256–1,000,000 之间的整数': 'Maximum output tokens must be an integer between 256 and 1,000,000',
  '请填写有效的 Base URL': 'Enter a valid Base URL',
  'Base URL 必须是 HTTP(S) 地址，密钥请填入 API Key': 'Base URL must use HTTP(S). Enter credentials in API Key.',
  '所选思考程度不在此内置模型支持的范围内': 'The selected reasoning effort is not supported by this built-in model',
  '请填写服务名称': 'Enter a server name',
  '请填写启动命令': 'Enter a launch command',
  'MCP URL 必须使用 HTTP(S)': 'The MCP URL must use HTTP(S)',
  '请填写完整的 HTTP(S) 端点地址': 'Enter a complete HTTP(S) endpoint URL',
  '加密环境变量需为字符串值的 JSON 对象': 'Encrypted environment variables must be a JSON object with string values',
  /* Desktop-interface errors: thrown by the main process and the worker, then shown verbatim in the stream. */
  '会话已删除': 'This session was deleted',
  '此会话不能访问桌面会话接口': 'This session cannot use the desktop session tools',
  '此会话不能访问工作台接口': 'This session cannot use the workbench tools',
  '此会话不能访问桌面设置接口': 'This session cannot use the desktop settings tools',
  '此会话不能访问桌面服务接口': 'This session cannot use the desktop service tools',
  '此会话不能定位桌面内容': 'This session cannot focus desktop content',
  '此会话不能读取待处理审批': 'This session cannot read pending approvals',
  '此会话不能读取任务产物': 'This session cannot read task artifacts',
  '此会话不能修改聊天草稿': 'This session cannot change the chat draft',
  '此会话不能读取草稿历史': 'This session cannot read draft history',
  '此会话不能恢复草稿历史': 'This session cannot restore draft history',
  '此会话不能修改聊天上下文': 'This session cannot change the chat context',
  '此会话不能读取聊天上下文': 'This session cannot read the chat context',
  '此会话不能读取聊天附件': 'This session cannot read chat attachments',
  '此会话不能修改聊天附件': 'This session cannot change chat attachments',
  '此会话不能预检聊天草稿': 'This session cannot preflight the chat draft',
  '此会话不能读取聊天草稿状态': 'This session cannot read the draft state',
  '此会话不能发送聊天草稿': 'This session cannot send the draft',
  '此会话不能读取上下文选项': 'This session cannot read context options',
  '此会话不能读取消息选项': 'This session cannot read message options',
  '此会话不能读取消息片段': 'This session cannot read message excerpts',
  '此会话不能读取排队消息': 'This session cannot read queued messages',
  '此会话不能撤回排队消息': 'This session cannot withdraw queued messages',
  '此会话不能管理排队消息': 'This session cannot manage queued messages',
  '此会话不能访问项目动作': 'This session cannot use project actions',
  '计划模式下不能修改桌面状态': 'Plan mode cannot change desktop state',
  '计划模式或拒绝策略下不能修改工作台': 'Plan mode or a deny policy cannot change the workbench',
  '计划模式或拒绝策略下不能修改设置': 'Plan mode or a deny policy cannot change settings',
  '计划模式或拒绝策略下不能执行此操作': 'Plan mode or a deny policy cannot run this action',
  '当前模式禁止运行项目动作': 'The current mode forbids running project actions',
  '此任务不能运行沙箱命令': 'This task cannot run sandboxed commands',
  '此任务无权取得 MCP 授权': 'This task cannot obtain MCP authorization',
  '请先为这个聊天绑定项目目录': 'Bind a project directory to this chat first',
  '模型不存在，请先用 get_harness 查看可用模型': 'That model does not exist. Use get_harness to list the available models',
  '该模型不允许此思考程度：': 'This model does not allow that reasoning level: ',
  '目录不属于此项目': 'The directory does not belong to this project',
  '目录不属于当前项目': 'The directory does not belong to the current project',
  '消息不属于当前会话': 'The message does not belong to this session',
  '消息不存在或不可引用': 'The message does not exist or cannot be quoted',
  '消息引用范围超出正文': 'The quoted range exceeds the message body',
  '消息过长，请先指定完整引用范围': 'The message is too long. Specify the full quoted range first',
  '消息内容已改变，请重新读取引用片段': 'The message changed. Read the quoted excerpt again',
  '创建会话失败': 'Creating the session failed',
  '未能创建快速聊天': 'Could not create the quick chat',
  '未能创建修订会话': 'Could not create the revision session',
  '未能创建侧聊': 'Could not create the side chat',
  '此次审查已经提交结果': 'This review already submitted its findings',
  '当前没有可搜索的浏览器标签页': 'There is no browser tab to search',
  '聊天草稿已变化，请先重新读取状态': 'The draft changed. Read its state again before retrying',
  '草稿附件已变化，请先重新读取': 'The draft attachments changed. Read them again before retrying',
  '草稿内容不能为空': 'The draft cannot be empty',
  '每次最多保留 10 个草稿附件': 'Keep at most 10 draft attachments',
  '排队消息已变化，请先重新读取': 'The queued messages changed. Read them again before retrying',
  '排队消息已开始处理，请先重新读取': 'A queued message already started. Read the queue again',
  '撤回排队消息未返回结果': 'Withdrawing the queued message returned no result',
  '引用已过期，请先刷新：': 'This reference expired. Refresh it first: ',
  '附件路径必须是项目相对路径': 'Attachment paths must be project-relative',
  '附件必须是普通文件：': 'Attachments must be regular files: ',
  '附件大小不能超过 10 MB': 'Attachments cannot exceed 10 MB',
  '附件大小不能超过 10 MB：': 'Attachment exceeds 10 MB: ',
  '子任务所选模型不存在，请检查模型设置': 'The selected model for this subagent no longer exists. Check the model settings',
  '项目动作配置已变化，请重新列出项目动作': 'The project actions changed. List them again',
  '项目动作退出码：': 'Project action exit code: ',
  '项目目录不存在或不可访问': 'The project directory is missing or inaccessible',
  '用户未批准此操作': 'The user did not approve this action',
  '用户未批准修改设置': 'The user did not approve changing settings',
  '用户未批准给其他会话发送消息': 'The user did not approve messaging another session',
  '用户未批准添加项目': 'The user did not approve adding a project',
  '用户未批准添加目录': 'The user did not approve adding a directory',
  '用户未批准移除目录': 'The user did not approve removing a directory',
  '用户未批准打开外部链接': 'The user did not approve opening the external link',
  '用户拒绝了本次操作': 'The user declined this action',
  '任务已停止': 'The task was stopped',
  '操作不存在': 'That operation does not exist',
  '桌面数据缺少版本信息': 'Desktop data has no version information',
  '无法识别桌面数据版本': 'Unrecognized desktop data version',
  '只能打开当前任务产物': "Only this task's artifacts can be opened",
  '请选择有效的任务产物': 'Choose a valid task artifact',
  '任务产物超过内置预览大小限制': 'The artifact exceeds the built-in preview size limit',
  '浏览器操作已取消': 'The browser action was cancelled',
  '找不到目标元素，请重新检查页面': 'Target element not found. Inspect the page again',
  '无法定位页面元素': 'Could not locate the page element',
  '请提供有效的键盘组合': 'Provide a valid key combination',
  '不支持的键盘按键：': 'Unsupported key: ',
  '请提供拖拽终点': 'Provide the drag destination',
  'Chrome 标签不存在或已关闭': 'The Chrome tab is missing or closed',
  'Chrome 标签授权已撤销或标签已关闭': 'The Chrome tab authorization was revoked or the tab closed',
  'Chrome 扩展来源不匹配': 'The Chrome extension origin does not match',
  'Chrome 扩展桥接未启用': 'The Chrome extension bridge is not enabled',
  '此 Chrome 标签正在执行操作，请等待完成': 'This Chrome tab is busy. Wait for the current action',
  '桥接加密载荷无效': 'The bridge payload encryption is invalid',
  '桥接载荷格式无效': 'The bridge payload format is invalid',
  '桥接请求过大': 'The bridge request is too large',
  '桥接请求格式无效': 'The bridge request format is invalid',
  'Chrome 桥接需要加密载荷': 'The Chrome bridge requires an encrypted payload',
  'Chrome 桥接已关闭': 'The Chrome bridge is closed',
  '无法启动 Chrome 桥接': 'Could not start the Chrome bridge',
  'Chrome 标签不存在或连接已过期': 'The Chrome tab is missing or the connection expired',
  'Chrome 标签已授权给其他任务，请先撤销原任务授权': 'This Chrome tab is authorized to another task. Revoke that authorization first',
  'Chrome 扩展连接已过期': 'The Chrome extension connection expired',
  '打开 Chrome 标签超时': 'Timed out opening the Chrome tab',
  '没有已连接且已授权的 Chrome 标签，请先在设置中连接并授权标签': 'No connected and authorized Chrome tab. Connect and authorize one in settings',
  '当前任务没有权限访问此 Chrome 标签': 'This task has no access to that Chrome tab',
  'Chrome 标签不是受支持的 HTTP(S) 页面': 'The Chrome tab is not a supported HTTP(S) page',
  'Chrome 返回的操作结果无效': 'Chrome returned an invalid action result',
  'Chrome 浏览器操作超时': 'The Chrome browser action timed out',
  'Chrome 桥接来源不受支持': 'The Chrome bridge origin is not supported',
  'Chrome 桥接请求主机无效': 'The Chrome bridge request host is invalid',
  'Chrome 扩展协议版本不受支持': 'The Chrome extension protocol version is not supported',
  'Chrome 扩展版本不受支持，请加载 Pi 提供的扩展': 'The Chrome extension version is not supported. Load the extension Pi provides',
  '配对码无效或已过期': 'The pairing code is invalid or expired',
  'Chrome 扩展已断开': 'The Chrome extension disconnected',
  'Pi 进程已关闭': 'The Pi process is closed',
  'Pi 操作超时': 'The Pi operation timed out',
  '恢复临时目录包含外部变更，未清理。\n': 'The restore temporary directory has outside changes and was not cleaned.\n',
  '待回收目录包含外部变更，未继续删除。\n': 'The directory to reclaim has outside changes; deletion stopped.\n',
  '恢复目录不属于原仓库，未修改文件': 'The restore directory does not belong to the original repository; no files were changed',
  '恢复目录文件被外部修改，未覆盖：': 'A restore directory file changed outside Pi and was not overwritten: ',
  '迁移期间文件发生变化：': 'The file changed during migration: ',
  '沙箱工作目录过宽，请选择具体项目目录': 'The sandbox working directory is too broad. Choose a specific project directory',
  'Worktree 执行目录不属于受管目录': 'The worktree working directory is not a managed directory',
  'Worktree 创建目录已存在，未覆盖现有文件': 'The worktree creation directory already exists; existing files were not overwritten',
  'Worktree 创建中断，现有文件已保留：': 'Worktree creation was interrupted; existing files were kept: ',
  'Worktree 注册失败，恢复目录已保留：': 'Worktree registration failed. The restore directory was kept: ',
  '任务创建失败，空 Worktree 已移除，但分支或快照清理未完成。\n': 'Task creation failed. The empty worktree was removed, but branch or snapshot cleanup did not finish.\n',
  '任务创建失败，Worktree 恢复目录已保留。请从项目 Worktree 列表重新打开。\n': 'Task creation failed. The worktree restore directory was kept; reopen it from the project worktree list.\n',
  '任务已创建，但环境初始化未能启动。请在项目动作中重试。\n': 'The task was created but environment initialization did not start. Retry from the project actions.\n',
  '任务窗口未能恢复，可从任务菜单重新打开。\n': 'The task window could not be restored. Reopen it from the task menu.\n',
  '聊天保存失败，清理目录时出现错误。原目录已保留。\n': 'Saving the chat failed while cleaning a directory. The original directory was kept.\n',
  '索引准备目录包含外部变更，未清理。\n': 'The index preparation directory has outside changes and was not cleaned.\n',
  '无法启动 OAuth 回调': 'Could not start the OAuth callback',
  '无法解压插件归档：': 'Could not unpack the plugin archive: ',
  '插件 Skill 无效：': 'Invalid plugin skill: ',
  '插件资源或 MCP 标识与已有配置冲突': 'The plugin resource or MCP id conflicts with the existing configuration',
  '浏览器截图操作已取消': 'The browser screenshot was cancelled',
  '存在未解决冲突，无法捕获轮次快照': 'Unresolved conflicts block capturing a turn snapshot',
  '轮次快照超过 20000 个文件，请调整项目忽略规则': 'The turn snapshot exceeds 20000 files. Adjust the project ignore rules',
  '轮次快照遇到不支持的文件类型': 'The turn snapshot hit an unsupported file type',
  '轮次快照超过容量限制，请调整项目忽略规则': 'The turn snapshot exceeds the size limit. Adjust the project ignore rules',
  '轮次快照返回了不完整的文件清单': 'The turn snapshot returned an incomplete file list',
  '捕获轮次快照时文件发生变化，请重试': 'Files changed while capturing the turn snapshot. Retry',
  '项目目录已在其他窗口修改，请重新打开后保存': 'The project directory changed in another window. Reopen it before saving',
  '当前系统没有可用的 Windows 沙箱；未执行命令': 'No Windows sandbox is available; the command was not run',
  '沙箱启动器校验失败，未执行命令；请使用完整的应用版本': 'The sandbox launcher failed validation; the command was not run. Use a complete application build',
  '沙箱初始化失败，未执行命令：': 'Sandbox initialization failed; the command was not run: ',
  '沙箱恢复失败，恢复记录已保留；未执行新命令：': 'Sandbox recovery failed; the recovery record was kept and no new command ran: ',
  '沙箱命令已取消': 'The sandboxed command was cancelled',
  '沙箱执行失败，未退回完全访问：': 'Sandbox execution failed and did not fall back to full access: ',
  '沙箱主进程服务不可用，未执行命令': 'The sandbox main service is unavailable; the command was not run',
  '沙箱返回了无效退出状态': 'The sandbox returned an invalid exit status',
  '只能归档 Pi 管理的独立 Worktree': 'Only standalone worktrees managed by Pi can be archived',
  '只能恢复 Pi 管理的独立 Worktree': 'Only standalone worktrees managed by Pi can be restored',
  '恢复目录包含非普通文件：': 'The restore directory contains a non-regular file: ',
  'Git 尚未登记完整 Worktree': 'Git has not registered the complete worktree yet',
  '迁移恢复对象校验失败：': 'Migration recovery validation failed: ',
  '迁移冲突，目标文件未修改：': 'Migration conflict; the target file was not modified: ',
  '迁移恢复记录保存失败，原始快照已保留。\n': 'Saving the migration recovery record failed; the original snapshot was kept.\n',
  '迁移临时文件类型已变化': 'The migration temporary file type changed',
  '桌面工具操作已取消或超时': 'The desktop tool action was cancelled or timed out',
  '会话尚未初始化': 'The session is not initialized yet',
  '此扩展的自定义 TUI 组件需要 Pi CLI；Desktop 支持标准确认、选择和输入框。': 'This extension\'s custom TUI component needs the Pi CLI. Desktop supports the standard confirm, select and input prompts.',
  'Desktop 不提供 TUI 主题，请检查 ctx.mode 后调用': 'Desktop has no TUI theme. Check ctx.mode before calling',
  '该二进制附件暂不支持，请选择文本或图片': 'Binary attachments are not supported yet. Choose text or an image',
  '当前会话还没有可分叉的消息': 'This session has no message to fork from yet',
  '扩展取消了会话分叉': 'The extension cancelled the fork',
  'MCP 工具列表包含重复名称：': 'The MCP tool list contains duplicate names: ',
  'MCP 工具列表返回重复分页标识，无法完成加载': 'The MCP tool list returned a repeated page cursor; loading cannot finish',
} as const;
/**
 * Errors that interpolate a value (a process exit code, a model id, a record id) can never be keyed by their
 * runtime text. Each pattern captures the values and rebuilds the sentence in English, so the boundary stays
 * the only place that translates and main/worker never need a locale.
 */
export const appErrorPatterns: Array<{ pattern: RegExp; render: (match: RegExpMatchArray) => string }> = [
  { pattern: /^Pi 进程退出（(.+)），可重新打开任务继续$/, render: match => 'The Pi process exited (' + match[1] + '). Reopen the task to continue' },
  { pattern: /^Pi 进程退出（(.+)），会话已保留$/, render: match => 'The Pi process exited (' + match[1] + '). The session was kept' },
  { pattern: /^Pi 中未找到 (.+)，请检查模型 ID 或改用自定义提供商$/, render: match => 'Pi could not find ' + match[1] + '. Check the model id or use a custom provider' },
  { pattern: /^(.+) 缺少启动命令$/, render: match => match[1] + ' has no launch command' },
  { pattern: /^迁移已停止，外部修改已保留；恢复记录 (.+)，需检查：(.+)$/, render: match => 'Migration stopped; outside changes were kept. Recovery record ' + match[1] + ', check: ' + match[2] },
];
