import { readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { expect, test } from '@playwright/test';
import type { Thread } from '../../src/shared/contracts.ts';
import { acceptanceApp } from './fixtures/acceptance-app.ts';
import { startDevelopmentSource } from './fixtures/development-source.ts';

let development: Awaited<ReturnType<typeof startDevelopmentSource>>;
let fixture: Awaited<ReturnType<typeof acceptanceApp>>;
test.beforeAll(async () => { development = await startDevelopmentSource(); });
test.afterAll(async () => { await development?.server.close(); });
test.beforeEach(async () => { fixture = await acceptanceApp(development.url); });
test.afterEach(async () => { if (fixture) { const errors = [...fixture.errors]; await fixture.close(); expect(errors).toEqual([]); } });
async function idle() { await expect.poll(async () => (await fixture.snapshot()).data.threads[0].status).toBe('idle'); }
const processButton = () => fixture.page.locator('[data-disclosure^="process:"] > .disclosure-header > button').last();
const groupButton = () => fixture.page.locator('[data-disclosure^="group:"] > .disclosure-header > button').last();

test('late tool calls preserve provisional prose and final collapse; choices survive task changes, reload and restart', async () => {
  fixture.setMode('hold'); fixture.setReasoning(true);
  await fixture.invoke({ op: 'thread.send', id: 't', text: '流式折叠验收', attachments: [] });
  await expect(fixture.page.locator('.turn-prose')).toContainText('验收流式内容');
  await expect(fixture.page.locator('.turn-answer')).toHaveCount(0);
  await expect(processButton()).toHaveAttribute('aria-expanded', 'true');
  fixture.releaseTool('read', { path: 'README.md' });
  await expect.poll(() => fixture.calls.length).toBe(2);
  await expect(groupButton()).toHaveAttribute('aria-expanded', 'false');
  await groupButton().click();
  await expect(fixture.page.locator('.activity-file-link')).toHaveText('README.md');
  const liveTool = (await fixture.snapshot()).data.threads[0].items.find(item => item.role === 'tool')!;
  expect(liveTool.startedAt).toBeGreaterThan(0); expect(liveTool.completedAt).toBeGreaterThanOrEqual(liveTool.startedAt!);
  await fixture.app.evaluate(({ shell }) => { shell.openPath = async path => { (globalThis as typeof globalThis & { openedPath?: string }).openedPath = path; return ''; }; });
  await fixture.page.locator('.activity-file-link').click();
  expect(await fixture.app.evaluate(() => (globalThis as typeof globalThis & { openedPath?: string }).openedPath)).toBe(join(fixture.project, 'README.md'));
  fixture.release(); await idle();
  await expect(fixture.page.locator('.turn-answer')).toContainText('验收回复完成');
  await expect(processButton()).toHaveAttribute('aria-expanded', 'false');
  await processButton().click();
  await expect(groupButton()).toHaveAttribute('aria-expanded', 'true');
  const thought = fixture.page.locator('[data-disclosure^="thinking:"]');
  await expect(thought).toHaveCount(2);
  await expect(thought.first().locator('button').first()).toHaveAttribute('aria-expanded', 'false');
  await thought.first().locator('button').first().click();
  await expect(thought.first()).toContainText('先读取实际文件');
  const choices = (await fixture.snapshot()).data.ui.threads.t.folds;
  expect(Object.values(choices).filter(Boolean).length).toBeGreaterThanOrEqual(3);
  const second = await fixture.invoke({ op: 'thread.create', projectId: 'p', worktree: false }) as Thread;
  const state = await fixture.snapshot();
  await fixture.invoke({ op: 'ui.update', ui: { ...state.data.ui, activeThreadId: second.id } });
  await expect(fixture.page.locator('.turn')).toHaveCount(0);
  await fixture.invoke({ op: 'ui.update', ui: { ...state.data.ui, activeThreadId: 't' } });
  await expect(groupButton()).toHaveAttribute('aria-expanded', 'true');
  await fixture.page.reload();
  await expect(processButton()).toHaveAttribute('aria-expanded', 'true');
  await fixture.restart();
  await expect(groupButton()).toHaveAttribute('aria-expanded', 'true');
  expect((await fixture.snapshot()).data.ui.threads.t.folds).toEqual(choices);
  await fixture.invoke({ op: 'thread.resume', id: 't' });
  await expect.poll(async () => JSON.parse((await fixture.snapshot()).data.threads.find(thread => thread.id === 't')?.items.find(item => item.id === liveTool.id)?.args ?? '{}')).toEqual(JSON.parse(liveTool.args!));
  const restored = (await fixture.snapshot()).data.threads.find(thread => thread.id === 't')!.items.find(item => item.id === liveTool.id)!;
  expect(restored.startedAt).toBe(liveTool.startedAt); expect(restored.completedAt).toBe(liveTool.completedAt);
});

test('edit waits for approval and shows real diff; write reports no invented additions', async () => {
  await fixture.invoke({ op: 'thread.update', id: 't', policy: 'ask' });
  fixture.requestTool('edit', { path: 'README.md', oldText: '# Acceptance', newText: '# Updated' });
  await fixture.invoke({ op: 'thread.send', id: 't', text: '审批编辑', attachments: [] });
  await expect(fixture.page.getByLabel('待审批操作')).toBeVisible();
  await expect(processButton()).toHaveAttribute('aria-expanded', 'true');
  await fixture.page.getByRole('button', { name: '允许这一次' }).click();
  await idle();
  await expect(processButton()).toHaveAttribute('aria-expanded', 'false');
  await processButton().click();
  await expect(processButton()).toHaveAttribute('aria-expanded', 'true');
  await groupButton().click();
  const edit = fixture.page.locator('[data-tool-kind="edit"]');
  await expect(edit.locator('.activity-stats')).toHaveText('+1−1');
  await edit.locator('.disclosure-toggle').first().focus();
  await fixture.page.keyboard.press('Enter');
  await expect(edit.getByLabel('文件修改差异')).toContainText('# Updated');
  expect(await readFile(join(fixture.project, 'README.md'), 'utf8')).toBe('# Updated\n');
  const tool = (await fixture.snapshot()).data.threads[0].items.find(item => item.toolName === 'edit')!;
  expect(tool.details?.diff).toContain('# Updated');
  await fixture.restart();
  await expect(fixture.page.getByLabel('文件修改差异')).toBeVisible();
  await fixture.invoke({ op: 'thread.update', id: 't', policy: 'auto' });
  fixture.requestTool('write', { path: 'written.txt', content: 'hello' });
  await fixture.invoke({ op: 'thread.send', id: 't', text: '写入验收', attachments: [] });
  await idle();
  await expect(processButton()).toHaveAttribute('aria-expanded', 'false');
  await processButton().click();
  await expect(processButton()).toHaveAttribute('aria-expanded', 'true');
  await groupButton().click();
  const write = fixture.page.locator('[data-tool-kind="write"]');
  await expect(write).toContainText('已写入');
  await expect(write.locator('.activity-stats')).toHaveCount(0);
  await expect(write.locator('.activity-diff')).toHaveCount(0);
});

test('stopping and provider failures leave process visible and recovery creates a new final answer', async () => {
  fixture.setMode('hold');
  await fixture.invoke({ op: 'thread.send', id: 't', text: '取消过程', attachments: [] });
  await expect(fixture.page.locator('.turn-prose')).toContainText('验收流式内容');
  await fixture.page.getByLabel('停止任务', { exact: true }).click();
  await idle();
  await expect(processButton()).toHaveAttribute('aria-expanded', 'true');
  await expect(fixture.page.locator('.turn-answer')).toHaveCount(0);
  fixture.release(); fixture.setMode('fail');
  await fixture.invoke({ op: 'thread.send', id: 't', text: '失败过程', attachments: [] });
  await expect.poll(async () => (await fixture.snapshot()).data.threads[0].status).toBe('error');
  // The failure stays visible as the red notice in the process line; no headline row and no retry card.
  await expect(fixture.page.locator('.notice.danger').filter({ hasText: 'ACCEPTANCE_PROVIDER_ERROR' })).toBeVisible();
  await expect(fixture.page.locator('.thread-error')).toHaveCount(0);
  await expect(fixture.page.locator('.turn-head')).toHaveCount(0);
  await expect(fixture.page.getByRole('button', { name: '继续 / 重试', exact: true })).toHaveCount(0);
  fixture.setMode('reply');
  await fixture.invoke({ op: 'thread.send', id: 't', text: '恢复过程', attachments: [] });
  await idle();
  await expect(fixture.page.locator('.turn-answer')).toHaveCount(1);
});
