import { taskAction } from './fixtures/task-actions.ts';
import { mkdir, rename, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { expect, test } from '@playwright/test';
import type { Thread } from '../../src/shared/contracts.ts';
import { acceptanceApp } from './fixtures/acceptance-app.ts';
import { startDevelopmentSource } from './fixtures/development-source.ts';

let development: Awaited<ReturnType<typeof startDevelopmentSource>>;
let fixture: Awaited<ReturnType<typeof acceptanceApp>>;
test.beforeAll(async () => { development = await startDevelopmentSource(); });
test.afterAll(async () => { await development?.server.close(); });
test.beforeEach(async () => {
  fixture = await acceptanceApp(development.url);
  await mkdir(join(fixture.project, 'src', 'pages'), { recursive: true });
  await mkdir(join(fixture.project, 'empty'));
  await writeFile(join(fixture.project, 'src', 'pages', '中文.txt'), '第一行\n查找内容\n末行');
  await writeFile(join(fixture.project, 'src', 'entry.txt'), 'entry');
  await writeFile(join(fixture.project, 'Alpha.txt'), 'alpha');
  await writeFile(join(fixture.project, 'Beta.txt'), 'beta');
  if (!await fixture.page.locator('.review-pane').isVisible()) await taskAction(fixture.page, '查看变更');
  await fixture.page.getByRole('button', { name: '新标签', exact: true }).click();
  await fixture.page.locator('.tool-launcher').getByRole('button', { name: '文件', exact: true }).click();
  await expect(fixture.page.getByRole('treeitem', { name: 'src', exact: true })).toBeVisible();
});
test.afterEach(async () => { if (fixture) { const errors = [...fixture.errors]; await fixture.close(); expect(errors).toEqual([]); } });

test('file tree supports one tab stop, complete keyboard navigation, typeahead and composition guards', async () => {
  const page = fixture.page;
  const src = page.getByRole('treeitem', { name: 'src', exact: true });
  const pages = page.getByRole('treeitem', { name: 'pages', exact: true });
  const file = page.getByRole('treeitem', { name: '中文.txt', exact: true });
  const tree = page.getByRole('tree', { name: '项目文件' });
  await expect(tree.locator('[role=treeitem][tabindex="0"]')).toHaveCount(1);
  await src.focus();
  await src.dispatchEvent('keydown', { key: 'ArrowRight', code: 'ArrowRight', isComposing: true, keyCode: 229 });
  await expect(src).toHaveAttribute('aria-expanded', 'false');
  await src.press('ArrowRight');
  await expect(src).toHaveAttribute('aria-expanded', 'true');
  await expect(pages).toHaveAttribute('aria-level', '2');
  expect(await src.evaluate(node => document.getElementById(node.getAttribute('aria-controls')!)?.getAttribute('role'))).toBe('group');
  await src.press('ArrowRight'); await expect(pages).toBeFocused();
  await pages.press('Enter'); await expect(file).toBeVisible();
  await pages.press('ArrowRight'); await expect(file).toBeFocused();
  await file.press('Enter');
  await expect(page.getByLabel('文件内容 src/pages/中文.txt', { exact: true })).toHaveValue('第一行\n查找内容\n末行');
  await expect(file).toHaveAttribute('aria-selected', 'true');
  await expect(file).toHaveAttribute('aria-level', '3');
  await file.press('ArrowLeft'); await expect(pages).toBeFocused();
  await pages.press('ArrowLeft'); await expect(file).toHaveCount(0);
  await pages.press('ArrowLeft'); await expect(src).toBeFocused();
  await src.press('Space'); await expect(pages).toHaveCount(0);
  await src.press('Home'); await expect(page.getByRole('treeitem', { name: 'empty', exact: true })).toBeFocused();
  await page.keyboard.press('End'); await expect(page.getByRole('treeitem', { name: 'README.md', exact: true })).toBeFocused();
  await page.keyboard.press('a'); await expect(page.getByRole('treeitem', { name: 'Alpha.txt', exact: true })).toBeFocused();
  await page.keyboard.press('Home'); await page.keyboard.press('ArrowDown'); await expect(src).toBeFocused();
  await page.keyboard.press('ArrowUp'); await expect(page.getByRole('treeitem', { name: 'empty', exact: true })).toBeFocused();
  await expect(tree.locator('[role=treeitem][tabindex="0"]')).toHaveCount(1);
  await page.keyboard.press('Tab');
  expect(await tree.evaluate(node => node.contains(document.activeElement))).toBe(false);
});

test('directory expansion and breadcrumb scope survive refresh, task changes and application restart', async () => {
  const page = fixture.page;
  await page.getByRole('treeitem', { name: 'src', exact: true }).click();
  await page.getByRole('treeitem', { name: 'pages', exact: true }).click();
  await page.getByRole('treeitem', { name: '中文.txt', exact: true }).click();
  await expect(page.getByLabel('文件内容 src/pages/中文.txt', { exact: true })).toBeVisible();
  await page.getByLabel('刷新文件列表').click();
  await expect(page.getByRole('treeitem', { name: '中文.txt', exact: true })).toBeVisible();
  await page.getByRole('treeitem', { name: '中文.txt', exact: true }).focus();
  await page.getByLabel('刷新文件列表').evaluate(node => (node as HTMLButtonElement).click());
  await expect(page.getByRole('treeitem', { name: '中文.txt', exact: true })).toBeFocused();
  await expect.poll(async () => (await fixture.snapshot()).data.ui.threads.t.expandedDirectories).toEqual(['src', 'src/pages']);
  await page.getByRole('button', { name: 'src ›', exact: true }).click();
  await expect(page.getByRole('navigation', { name: '文件目录' }).getByRole('button', { name: 'src', exact: true })).toHaveAttribute('aria-current', 'location');
  await expect(page.getByRole('treeitem', { name: 'pages', exact: true })).toHaveAttribute('aria-level', '1');
  await page.getByRole('treeitem', { name: 'entry.txt', exact: true }).focus();
  await expect.poll(async () => (await fixture.snapshot()).data.ui.threads.t.fileTreeFocus).toBe('src/entry.txt');
  await fixture.invoke({ op: 'ui.threadPatch', threadId: 't', patch: { draft: { text: '保留草稿', attachments: [] }, folds: { example: true } } });
  const other = await fixture.invoke({ op: 'thread.create', projectId: 'p', worktree: false }) as Thread;
  await page.locator('.thread-main').filter({ hasText: other.title }).click();
  if (!await page.locator('.review-pane').isVisible()) await taskAction(page, '查看变更');
  await page.getByRole('button', { name: '新标签', exact: true }).click();
  await page.locator('.tool-launcher').getByRole('button', { name: '文件', exact: true }).click();
  await expect(page.getByRole('treeitem', { name: 'src', exact: true })).toHaveAttribute('aria-expanded', 'false');
  await page.locator('.thread-main').filter({ hasText: '验收任务' }).click();
  await expect(page.getByRole('treeitem', { name: 'pages', exact: true })).toHaveAttribute('aria-expanded', 'true');
  await expect(page.getByRole('treeitem', { name: 'entry.txt', exact: true })).toHaveAttribute('tabindex', '0');
  await fixture.restart();
  const restored = fixture.page;
  await expect(restored.getByRole('treeitem', { name: 'entry.txt', exact: true })).toHaveAttribute('tabindex', '0');
  const state = (await fixture.snapshot()).data.ui.threads.t;
  expect(state.fileDirectory).toBe('src'); expect(state.expandedDirectories).toEqual(['src', 'src/pages']);
  expect(state.draft?.text).toBe('保留草稿'); expect(state.folds.example).toBe(true);
  await restored.getByRole('navigation', { name: '文件目录' }).getByRole('button', { name: '项目', exact: true }).click();
  await expect(restored.getByRole('treeitem', { name: 'src', exact: true })).toHaveAttribute('aria-expanded', 'true');
});

test('directory failures offer retry, empty folders are explicit and removed focus falls back to its parent', async () => {
  const page = fixture.page;
  await page.getByRole('treeitem', { name: 'empty', exact: true }).click();
  await expect(page.getByRole('treeitem', { name: 'empty', exact: true }).locator('.file-tree-note')).toHaveText('空目录');
  await rename(join(fixture.project, 'src'), join(fixture.project, 'moved'));
  await page.getByRole('treeitem', { name: 'src', exact: true }).click();
  await expect(page.locator('.file-navigation-error')).toContainText('src 加载失败');
  await rename(join(fixture.project, 'moved'), join(fixture.project, 'src'));
  await page.getByRole('button', { name: '重试目录 src', exact: true }).click();
  await expect(page.getByRole('treeitem', { name: 'pages', exact: true })).toBeVisible();
  await expect(page.locator('.file-navigation-error')).toHaveCount(0);
  await page.getByRole('treeitem', { name: 'pages', exact: true }).click();
  await page.getByRole('treeitem', { name: '中文.txt', exact: true }).focus();
  await expect.poll(async () => (await fixture.snapshot()).data.ui.threads.t.fileTreeFocus).toBe('src/pages/中文.txt');
  await rm(join(fixture.project, 'src', 'pages', '中文.txt'));
  await page.getByLabel('刷新文件列表').click();
  await expect(page.getByRole('treeitem', { name: 'pages', exact: true }).locator('.file-tree-note')).toHaveText('空目录');
  await expect(page.getByRole('treeitem', { name: 'pages', exact: true })).toHaveAttribute('tabindex', '0');
  await expect(page.getByLabel('刷新文件列表')).toBeFocused();
  await expect(page.getByRole('treeitem', { name: '中文.txt', exact: true })).toHaveCount(0);
});

test('Unicode directory names with spaces retain valid accessibility references and an empty tree stays focusable', async () => {
  const page = fixture.page;
  await mkdir(join(fixture.project, '含 空格'));
  await writeFile(join(fixture.project, '含 空格', 'note.txt'), 'hello');
  await page.getByLabel('刷新文件列表').click();
  const directory = page.getByRole('treeitem', { name: '含 空格', exact: true });
  await directory.click();
  await expect(page.getByRole('treeitem', { name: 'note.txt', exact: true })).toBeVisible();
  expect(await directory.evaluate(node => {
    const ids = node.getAttribute('aria-controls')!.split(/\s+/);
    return ids.length === 1 && document.getElementById(ids[0])?.getAttribute('role') === 'group';
  })).toBe(true);
  await page.getByRole('treeitem', { name: 'note.txt', exact: true }).click();
  await page.getByRole('button', { name: '含 空格 ›', exact: true }).click();
  await page.getByRole('button', { name: '关闭文件 含 空格/note.txt', exact: true }).click();
  await rm(join(fixture.project, '含 空格', 'note.txt'));
  await page.getByLabel('刷新文件列表').click();
  await expect(page.locator('.file-navigator').getByRole('status')).toHaveText('此目录为空');
  const tree = page.getByRole('tree', { name: '项目文件' });
  await tree.focus(); await expect(tree).toBeFocused();
  expect(await tree.evaluate(node => node.getBoundingClientRect().height)).toBeGreaterThanOrEqual(28);
  await page.getByRole('navigation', { name: '文件目录' }).getByRole('button', { name: '项目', exact: true }).click();
  await expect(directory).toHaveAccessibleDescription('空目录');
});

test('file search clears obsolete results, defers Chinese composition and opens actual content locations', async () => {
  const page = fixture.page;
  const input = page.getByRole('textbox', { name: '搜索项目文件', exact: true });
  const results = page.getByRole('region', { name: '文件搜索结果' });
  await input.fill('Alpha');
  await expect(results.getByRole('button', { name: 'Alpha.txt', exact: true })).toBeVisible();
  await input.fill('does-not-exist');
  await expect(results.getByRole('button', { name: 'Alpha.txt', exact: true })).toHaveCount(0);
  await expect(results.getByRole('status')).toHaveText('没有找到匹配的文件或内容');
  await input.dispatchEvent('compositionstart');
  await input.fill('中');
  await expect(results.getByRole('status')).toHaveText('输入完成后搜索');
  await expect(results.locator('button')).toHaveCount(0);
  await input.fill('中文'); await input.dispatchEvent('compositionend');
  await expect(results.locator('.file-search-result')).toHaveCount(1);
  await page.getByLabel('内容', { exact: true }).check();
  await input.fill('查找内容');
  await results.locator('.file-search-result').filter({ hasText: '查找内容' }).click();
  const editor = page.getByLabel('文件内容 src/pages/中文.txt', { exact: true });
  await expect(editor).toBeFocused();
  expect(await editor.evaluate(node => (node as HTMLTextAreaElement).selectionStart)).toBe(4);
  await input.fill('   ');
  await expect(results).toHaveCount(0);
  await expect(page.getByRole('tree', { name: '项目文件' })).toBeVisible();
});

test('search failures remain actionable and configured tree shortcuts persist without intercepting text editing', async () => {
  const page = fixture.page;
  const query = page.getByRole('textbox', { name: '搜索项目文件', exact: true });
  // A background Git status process may still hold its Windows working directory briefly.
  await expect(async () => rename(fixture.project, fixture.project + '-moved')).toPass({ timeout: 5000 });
  try {
    await query.fill('Alpha');
    await expect(page.locator('.file-navigation-error')).toContainText('搜索失败');
  } finally { await rename(fixture.project + '-moved', fixture.project); }
  await page.getByRole('button', { name: '重试搜索', exact: true }).click();
  await expect(page.getByRole('region', { name: '文件搜索结果' }).getByRole('button', { name: 'Alpha.txt', exact: true })).toBeVisible();
  await query.fill('');
  await page.keyboard.press('Control+,');
  await page.getByRole('button', { name: '键盘快捷键', exact: true }).click();
  const shortcut = page.getByLabel('文件树：下一项 快捷键', { exact: true });
  await expect(shortcut).toHaveValue('ArrowDown');
  await shortcut.press('Control+k');
  await expect(page.locator('.settings-page').getByRole('alert')).toContainText('使用相同快捷键');
  await shortcut.press('Alt+ArrowDown');
  await page.getByRole('button', { name: '保存设置', exact: true }).click();
  await expect(page.locator('.form-feedback')).toHaveText('设置已保存');
  await page.getByRole('button', { name: '返回工作台', exact: true }).click();
  const empty = page.getByRole('treeitem', { name: 'empty', exact: true });
  await empty.focus(); await empty.press('ArrowDown'); await expect(empty).toBeFocused();
  await empty.press('Alt+ArrowDown'); await expect(page.getByRole('treeitem', { name: 'src', exact: true })).toBeFocused();
  await query.focus(); await query.press('Alt+ArrowDown'); await expect(query).toBeFocused();
  await fixture.restart();
  expect((await fixture.snapshot()).data.settings.shortcuts?.fileNext).toBe('Alt+ArrowDown');
  await fixture.page.getByRole('treeitem', { name: 'empty', exact: true }).focus();
  await fixture.page.keyboard.press('Alt+ArrowDown');
  await expect(fixture.page.getByRole('treeitem', { name: 'src', exact: true })).toBeFocused();
  await fixture.page.keyboard.press('Control+,');
  await fixture.page.getByRole('button', { name: '键盘快捷键', exact: true }).click();
  await fixture.page.getByRole('button', { name: '恢复默认快捷键', exact: true }).click();
  await fixture.page.getByRole('button', { name: '保存设置', exact: true }).click();
  await expect(fixture.page.locator('.form-feedback')).toHaveText('设置已保存');
  await fixture.page.getByRole('button', { name: '返回工作台', exact: true }).click();
  await fixture.page.getByRole('treeitem', { name: 'empty', exact: true }).focus();
  await fixture.page.keyboard.press('ArrowDown');
  await expect(fixture.page.getByRole('treeitem', { name: 'src', exact: true })).toBeFocused();
});

test('search paginates beyond two hundred matches, retains previous pages and opens the selected line', async () => {
  const page = fixture.page;
  const lines = Array.from({ length: 451 }, (_, index) => '分页目标 ' + (index + 1));
  await writeFile(join(fixture.project, 'many.txt'), lines.join('\n'));
  await page.getByLabel('内容', { exact: true }).check();
  await page.getByRole('textbox', { name: '搜索项目文件', exact: true }).fill('分页目标');
  const results = page.getByRole('region', { name: '文件搜索结果' });
  const pagination = results.getByRole('navigation', { name: '搜索结果分页' });
  await expect(results).toHaveAttribute('aria-busy', 'false');
  await expect(results.locator('.file-search-result')).toHaveCount(200);
  await expect(pagination).toContainText('第 1 页');
  await pagination.getByRole('button', { name: '下一页', exact: true }).focus();
  await page.keyboard.press('Enter');
  await expect(pagination).toContainText('第 2 页');
  await expect(results.locator('.file-search-result').first()).toContainText('many.txt:201');
  await pagination.getByRole('button', { name: '下一页', exact: true }).click();
  await expect(pagination).toContainText('第 3 页');
  await expect(results.locator('.file-search-result')).toHaveCount(51);
  await expect(results.getByRole('status')).toHaveText('找到 451 条结果');
  await expect(pagination.getByRole('button', { name: '下一页', exact: true })).toBeDisabled();
  await pagination.getByRole('button', { name: '上一页', exact: true }).click();
  await expect(results.locator('.file-search-result').first()).toContainText('many.txt:201');
  await results.locator('.file-search-result').first().click();
  const editor = page.getByLabel('文件内容 many.txt', { exact: true });
  await expect(editor).toBeFocused();
  expect(await editor.evaluate(node => (node as HTMLTextAreaElement).selectionStart)).toBe(lines.slice(0, 200).join('\n').length + 1);
  await pagination.getByRole('button', { name: '上一页', exact: true }).click();
  await expect(results.locator('.file-search-result').first()).toContainText('many.txt:1');
  await expect(results.locator('.file-search-result')).toHaveCount(200);
});

test('search cancellation keeps the interface responsive and obsolete requests cannot overwrite another query or task', async () => {
  const page = fixture.page;
  await writeFile(join(fixture.project, 'long-scan.txt'), 'miss\n'.repeat(1_000_000));
  const query = page.getByRole('textbox', { name: '搜索项目文件', exact: true });
  const results = page.getByRole('region', { name: '文件搜索结果' });
  await page.getByLabel('内容', { exact: true }).check();
  await query.fill('不存在的目标');
  await expect(results.locator('.file-search-progress')).toBeVisible();
  await results.getByRole('button', { name: '停止搜索', exact: true }).click();
  await expect(results.getByRole('status')).toHaveText('搜索已停止，已找到 0 条结果');
  await expect(results.getByRole('button', { name: '重新搜索', exact: true })).toBeFocused();
  await expect(results).toHaveAttribute('aria-busy', 'false');
  await expect(results.locator('.file-search-result')).toHaveCount(0);
  await results.getByRole('button', { name: '重新搜索', exact: true }).click();
  await expect(results).toHaveAttribute('aria-busy', 'true');
  await page.getByLabel('内容', { exact: true }).uncheck();
  await query.fill('Alpha');
  await expect(results.getByRole('status')).toHaveText('找到 1 条结果');
  await expect(results.locator('.file-search-result')).toHaveText('Alpha.txt');
  await page.getByLabel('内容', { exact: true }).check();
  await query.fill('miss');
  await expect(results.locator('.file-search-result')).toHaveCount(200);
  const other = await fixture.invoke({ op: 'thread.create', projectId: 'p', worktree: false }) as Thread;
  await page.locator('.thread-main').filter({ hasText: other.title }).click();
  if (!await page.locator('.review-pane').isVisible()) await taskAction(page, '查看变更');
  await page.getByRole('button', { name: '新标签', exact: true }).click();
  await page.locator('.tool-launcher').getByRole('button', { name: '文件', exact: true }).click();
  await expect(page.getByRole('tree', { name: '项目文件' })).toBeVisible();
  await query.fill('Beta');
  await expect(results.locator('.file-search-result')).toHaveText('Beta.txt');
  await expect(page.locator('.file-navigation-error')).toHaveCount(0);
  await page.locator('.thread-main').filter({ hasText: '验收任务' }).click();
  await expect(query).toHaveValue('');
  await expect(results).toHaveCount(0);
});

test('content search reports unsupported files and finds content beyond the editor preview limit', async () => {
  const page = fixture.page;
  await writeFile(join(fixture.project, 'beyond-preview.txt'), 'x'.repeat(520000) + '\n预览外的目标\n');
  await writeFile(join(fixture.project, 'binary.bin'), Buffer.from([0, 1]));
  await writeFile(join(fixture.project, 'legacy.txt'), Buffer.from([0xff, 0xfe, 1]));
  await page.getByLabel('内容', { exact: true }).check();
  await page.getByRole('textbox', { name: '搜索项目文件', exact: true }).fill('预览外的目标');
  const results = page.getByRole('region', { name: '文件搜索结果' });
  await expect(results.getByRole('status')).toHaveText('找到 1 条结果');
  await expect(results.locator('.file-search-result')).toContainText('beyond-preview.txt:2');
  await expect(results.locator('.file-search-coverage')).toHaveText('未检索内容：二进制 1、非 UTF-8 1。结果未覆盖这些项目。');
  await expect(results.locator('.file-search-progress')).toContainText('已排除 1 个依赖或生成目录');
});

test('an exactly full final page keeps keyboard focus and disabled pagination cannot restart scanning', async () => {
  const page = fixture.page;
  await writeFile(join(fixture.project, 'exact-page.txt'), '恰好一页\n'.repeat(200));
  await page.getByLabel('内容', { exact: true }).check();
  await page.getByRole('textbox', { name: '搜索项目文件', exact: true }).fill('恰好一页');
  const results = page.getByRole('region', { name: '文件搜索结果' });
  const next = results.getByRole('button', { name: '下一页', exact: true });
  await expect(results.locator('.file-search-result')).toHaveCount(200);
  await next.focus(); await next.press('Enter');
  await expect(results.getByRole('status')).toHaveText('找到 200 条结果');
  await expect(next).toBeFocused();
  await expect(next).toHaveAttribute('aria-disabled', 'true');
  await next.press('Enter');
  await expect(results).toHaveAttribute('aria-busy', 'false');
  await expect(results.getByRole('navigation', { name: '搜索结果分页' })).toContainText('第 1 页');
  await expect(results.locator('.file-search-result')).toHaveCount(200);
  for (const width of [1000, 1280, 1440]) {
    await fixture.app.evaluate(({ BrowserWindow }, width) => BrowserWindow.getAllWindows()[0].setSize(width, width === 1000 ? 640 : 940), width);
    const pagination = results.getByRole('navigation', { name: '搜索结果分页' });
    expect(await pagination.evaluate(element => element.scrollWidth <= element.clientWidth + 1)).toBe(true);
    await expect(next).toBeFocused();
  }
});
