import { taskAction } from './fixtures/task-actions.ts';
import { access, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { expect, test } from '@playwright/test';
import type { GitRange, HunkRecoveryListing, HunkRecoveryRecord } from '../../src/shared/git-ranges.ts';
import { diffHunks } from '../../src/shared/git-patches.ts';
import { gitRun } from '../../src/main/git.ts';
import { acceptanceApp } from './fixtures/acceptance-app.ts';
import { startDevelopmentSource } from './fixtures/development-source.ts';

let development: Awaited<ReturnType<typeof startDevelopmentSource>>;
let fixture: Awaited<ReturnType<typeof acceptanceApp>>;
test.beforeAll(async () => { development = await startDevelopmentSource(); });
test.afterAll(async () => { await development?.server.close(); });
test.beforeEach(async () => { fixture = await acceptanceApp(development.url); });
test.afterEach(async () => {
  if (fixture) { const errors = [...fixture.errors]; await fixture.close(); await expect(access(fixture.storage)).rejects.toMatchObject({ code: 'ENOENT' }); expect(errors).toEqual([]); }
});
test('latest run diff persists across restart and distinguishes run workspace changes from committed branch changes', async () => {
  const index = await readFile(join(fixture.project, '.git', 'index'));
  fixture.setMode('hold'); fixture.requestTool('write', { path: 'generated.txt', content: 'produced by task\n' });
  await fixture.invoke({ op: 'thread.send', id: 't', text: 'make file', attachments: [] });
  await expect.poll(() => readFile(join(fixture.project, 'generated.txt'), 'utf8').catch(() => '')).toBe('produced by task\n');
  await writeFile(join(fixture.project, 'external.txt'), 'external editor change\n');
  fixture.release();
  await expect.poll(async () => (await fixture.snapshot()).data.threads.find(thread => thread.id === 't')?.status, { timeout: 30000 }).toBe('idle');
  const range = await fixture.invoke({ op: 'git.range', threadId: 't', mode: 'turn', ref: '', path: '' }) as GitRange;
  expect(range.attribution).toBe('workspace'); expect(range.diff).toContain('external editor change'); expect(range.diff).toContain('produced by task');
  expect(await readFile(join(fixture.project, '.git', 'index'))).toEqual(index);
  await taskAction(fixture.page, '查看变更');
  await fixture.page.getByLabel('差异范围', { exact: true }).selectOption('turn');
  await expect(fixture.page.getByText('本次运行开始至结束的工作区快照，包含追加消息及可能的外部修改，不代表 Pi 独占改动。', { exact: true })).toBeVisible();
  await fixture.page.getByRole('button', { name: '新增 generated.txt', exact: true }).click();
  await expect(fixture.page.locator('.diff')).toContainText('produced by task');
  await fixture.restart();
  expect((await fixture.invoke({ op: 'git.range', threadId: 't', mode: 'turn', ref: '', path: '' }) as GitRange).diff).toBe(range.diff);
  await gitRun(fixture.project, ['switch', '-c', 'feature']);
  await gitRun(fixture.project, ['add', '--', 'generated.txt']); await gitRun(fixture.project, ['commit', '-m', 'task output']);
  const branch = await fixture.invoke({ op: 'git.range', threadId: 't', mode: 'branch', ref: 'main', path: '' }) as GitRange;
  expect(branch.attribution).toBe('branch'); expect(branch.files.map(file => file.path)).toEqual(['generated.txt']); expect(branch.diff).not.toContain('external editor');
});
test('hunk revert and recovery are actionable in the UI, survive restart and keep staged content unchanged', async () => {
  const baseline = Array.from({ length: 25 }, (_, i) => 'line ' + i).join('\n') + '\n';
  await writeFile(join(fixture.project, 'README.md'), baseline); await gitRun(fixture.project, ['add', '--', 'README.md']); await gitRun(fixture.project, ['commit', '-m', 'hunks']);
  const changed = baseline.replace('line 1\n', 'first change\n').replace('line 20\n', 'last change\n');
  await writeFile(join(fixture.project, 'README.md'), changed);
  const index = await readFile(join(fixture.project, '.git', 'index'));
  const { data } = await fixture.snapshot();
  await fixture.invoke({ op: 'ui.threadPatch', threadId: 't', patch: { selectedPath: 'README.md', reviewTab: 'changes' } });
  await fixture.invoke({ op: 'ui.update', ui: { ...data.ui, reviewOpen: true } });
  await fixture.page.getByRole('button', { name: '撤销此差异块', exact: true }).click();
  await expect.poll(() => readFile(join(fixture.project, 'README.md'), 'utf8')).toBe(baseline.replace('line 20\n', 'last change\n'));
  expect(await readFile(join(fixture.project, '.git', 'index'))).toEqual(index);
  const listing = await fixture.invoke({ op: 'git.recoveries', threadId: 't' }) as HunkRecoveryListing; expect(listing.records).toHaveLength(1); expect(listing.errors).toEqual([]);
  await fixture.restart();
  await fixture.page.getByRole('button', { name: 'Git 操作', exact: true }).click();
  await fixture.page.getByText('差异块恢复记录', { exact: true }).click();
  await fixture.page.getByRole('button', { name: '恢复撤销前版本', exact: true }).click();
  await expect.poll(() => readFile(join(fixture.project, 'README.md'), 'utf8')).toBe(changed);
  await expect(fixture.page.getByRole('button', { name: '已恢复', exact: true })).toBeDisabled();
});

test('hunk recovery disk failures retain the file and damaged history does not block a valid restore after restart', async () => {
  const original = await readFile(join(fixture.project, 'README.md'), 'utf8');
  const changed = original + 'keep this edit\n'; await writeFile(join(fixture.project, 'README.md'), changed);
  const index = await readFile(join(fixture.project, '.git', 'index'));
  const patch = diffHunks(await fixture.invoke({ op: 'git.diff', threadId: 't', path: 'README.md', mode: 'all' }) as string)[0];
  const version = await fixture.invoke({ op: 'git.hunkVersion', threadId: 't', path: 'README.md' }) as string;
  const record = await fixture.invoke({ op: 'git.hunkRevert', threadId: 't', path: 'README.md', patch, version, mode: 'all' }) as HunkRecoveryRecord;
  const blocked = join(fixture.storage, 'recovery', 'hunks', record.id, 'record.json.tmp'); await mkdir(blocked);
  const brokenId = crypto.randomUUID(); const broken = join(fixture.storage, 'recovery', 'hunks', brokenId); await mkdir(broken); await writeFile(join(broken, 'record.json'), '{');
  await taskAction(fixture.page, '查看变更');
  await fixture.page.getByRole('button', { name: 'Git 操作', exact: true }).click();
  await fixture.page.getByText('差异块恢复记录', { exact: true }).click();
  await expect(fixture.page.getByRole('alert').filter({ hasText: '部分恢复记录无法读取' })).toBeVisible();
  await fixture.page.getByRole('button', { name: '恢复撤销前版本', exact: true }).click();
  await expect(fixture.page.locator('.git-feedback')).toContainText(/EISDIR|EPERM|EACCES/);
  expect(await readFile(join(fixture.project, 'README.md'), 'utf8')).toBe(original);
  expect(JSON.parse(await readFile(join(fixture.storage, 'recovery', 'hunks', record.id, 'record.json'), 'utf8')).state).toBe('applied');
  await rm(blocked, { recursive: true }); await fixture.restart();
  await fixture.page.getByRole('button', { name: 'Git 操作', exact: true }).click();
  await fixture.page.getByText('差异块恢复记录', { exact: true }).click();
  await expect(fixture.page.getByRole('alert').filter({ hasText: '部分恢复记录无法读取' })).toBeVisible();
  await fixture.page.getByRole('button', { name: '恢复撤销前版本', exact: true }).click();
  await expect(fixture.page.getByRole('button', { name: '已恢复', exact: true })).toBeDisabled();
  expect(await readFile(join(fixture.project, 'README.md'), 'utf8')).toBe(changed);
  expect(await readFile(join(fixture.project, '.git', 'index'))).toEqual(index);
  await rm(broken, { recursive: true });
  await fixture.page.getByRole('button', { name: '刷新恢复记录', exact: true }).click();
  await expect(fixture.page.getByRole('alert')).toHaveCount(0);
});

test('interrupted hunk receipts are reconciled on restart without automatically rewriting project files', async () => {
  const path = join(fixture.project, 'README.md'); const original = await readFile(path, 'utf8'); const changed = original + 'recover me\n';
  await writeFile(path, changed);
  const patch = diffHunks(await fixture.invoke({ op: 'git.diff', threadId: 't', path: 'README.md', mode: 'all' }) as string)[0];
  const version = await fixture.invoke({ op: 'git.hunkVersion', threadId: 't', path: 'README.md' }) as string;
  const record = await fixture.invoke({ op: 'git.hunkRevert', threadId: 't', path: 'README.md', patch, version, mode: 'all' }) as HunkRecoveryRecord;
  const journal = join(fixture.storage, 'recovery', 'hunks', record.id, 'record.json');
  await writeFile(journal, JSON.stringify({ ...record, state: 'prepared' }));
  await fixture.restart();
  expect((await fixture.invoke({ op: 'git.recoveries', threadId: 't' }) as HunkRecoveryListing).records[0].state).toBe('applied');
  expect(await readFile(path, 'utf8')).toBe(original);
  await writeFile(journal, JSON.stringify({ ...record, state: 'restoring' })); await writeFile(path, changed);
  await fixture.restart();
  await taskAction(fixture.page, '查看变更');
  await fixture.page.getByRole('button', { name: 'Git 操作', exact: true }).click();
  await fixture.page.getByText('差异块恢复记录', { exact: true }).click();
  await expect(fixture.page.getByRole('button', { name: '完成恢复记录', exact: true })).toBeEnabled();
  expect(await readFile(path, 'utf8')).toBe(changed);
  expect(JSON.parse(await readFile(journal, 'utf8')).state).toBe('restoring');
  await fixture.page.getByRole('button', { name: '完成恢复记录', exact: true }).click();
  await expect(fixture.page.getByRole('button', { name: '已恢复', exact: true })).toBeDisabled();
  expect(JSON.parse(await readFile(journal, 'utf8')).state).toBe('restored');
});
