import { writeFile, readFile, unlink } from 'node:fs/promises';
import { join } from 'node:path';
import { expect, test } from '@playwright/test';
import { acceptanceApp } from './fixtures/acceptance-app.ts';
import { startDevelopmentSource } from './fixtures/development-source.ts';
import type { Thread } from '../../src/shared/contracts.ts';
import { contextDetailSchema, type ComposerPayload } from '../../src/shared/composer.ts';

let development: Awaited<ReturnType<typeof startDevelopmentSource>>;
let fixture: Awaited<ReturnType<typeof acceptanceApp>>;
test.beforeAll(async () => { development = await startDevelopmentSource(); });
test.afterAll(async () => { await development?.server.close(); });
test.beforeEach(async () => { fixture = await acceptanceApp(development.url); });
test.afterEach(async () => { const errors = [...fixture.errors]; await fixture.close(); expect(errors).toEqual([]); });

test('sent context is captured separately, searchable and restored while source files can change', async () => {
  await writeFile(join(fixture.project, 'README.md'), 'SNAPSHOT_ONLY_CONTENT 发送时\n');
  await fixture.invoke({ op: 'thread.send', id: 't', text: '请阅读这份文件', attachments: [], context: [{ kind: 'file', id: 'README.md', label: 'README.md', directoryId: 'p' }] });
  await expect.poll(async () => (await fixture.snapshot()).data.threads[0].status).toBe('idle');
  const user = fixture.page.locator('.message.user').last();
  await expect(user.locator('.markdown')).toHaveText('请阅读这份文件');
  await expect(user.locator('pre')).toHaveCount(0);
  expect(JSON.stringify(fixture.calls[0])).toContain('SNAPSHOT_ONLY_CONTENT');
  const snapshot = (await fixture.snapshot()).data.threads[0].items.find(item => item.role === 'user')!;
  expect(snapshot.input?.text).toBe('请阅读这份文件');
  await writeFile(join(fixture.project, 'README.md'), 'NEW_DISK_VERSION\n');
  await fixture.page.keyboard.press('Control+f');
  const find = fixture.page.getByRole('combobox', { name: '当前对话查找' });
  await find.fill('发送时');
  await expect(fixture.page.getByRole('dialog').getByRole('option')).toHaveCount(1);
  await find.press('Enter');
  await expect(user.locator('.message-context-content[data-search-active]')).toBeFocused();
  expect(await fixture.page.evaluate(() => {
    const range = CSS.highlights.get('conversation-find')?.values().next().value;
    return range instanceof Range && !!range.startContainer.parentElement?.closest('pre');
  })).toBe(true);
  await expect(user.locator('.message-context-content pre')).toContainText('SNAPSHOT_ONLY_CONTENT');
  await user.getByRole('button', { name: '打开来源', exact: true }).click();
  await expect(fixture.page.getByLabel('文件内容 README.md', { exact: true })).toHaveValue('NEW_DISK_VERSION\n');
  await fixture.restart();
  await expect(fixture.page.locator('.message.user .markdown')).toHaveText('请阅读这份文件');
  await expect(fixture.page.locator('.message-context-content pre')).toContainText('SNAPSHOT_ONLY_CONTENT');
  expect(await readFile(join(fixture.project, 'README.md'), 'utf8')).toBe('NEW_DISK_VERSION\n');
});

test('queued input metadata follows edited reordered messages into session history', async () => {
  fixture.setMode('hold');
  await fixture.invoke({ op: 'thread.send', id: 't', text: '主任务', attachments: [] });
  await expect.poll(() => fixture.calls.length).toBe(1);
  await fixture.invoke({ op: 'thread.send', id: 't', text: '第一条', attachments: [], queue: 'followUp', context: [{ kind: 'file', id: 'README.md', label: '第一条引用' }] });
  await fixture.invoke({ op: 'thread.send', id: 't', text: '第二条', attachments: [], queue: 'followUp', context: [{ kind: 'file', id: 'README.md', label: '第二条引用' }] });
  const queue = (await fixture.snapshot()).data.threads[0].queue!;
  await fixture.invoke({ op: 'thread.queueChange', threadId: 't', change: { id: queue[1].id!, revision: queue[1].revision!, action: 'up' } });
  await fixture.invoke({ op: 'thread.queueChange', threadId: 't', change: { id: queue[1].id!, revision: queue[1].revision!, action: 'edit', text: '修改后的第二条' } });
  fixture.release();
  await expect.poll(async () => (await fixture.snapshot()).data.threads[0].items.filter(item => item.role === 'user').map(item => item.input?.text)).toEqual(['主任务', '修改后的第二条', '第一条']);
  await expect.poll(async () => (await fixture.snapshot()).data.threads[0].status).toBe('idle');
  await fixture.restart();
  expect((await fixture.snapshot()).data.threads[0].items.filter(item => item.role === 'user').map(item => item.input?.parts[0]?.label)).toEqual([undefined, '第二条引用', '第一条引用']);
});

test('editing from the first turn branches before that message, preserves files and draft, and restarts before sending', async () => {
  await fixture.invoke({ op: 'thread.send', id: 't', text: 'original first question', attachments: [] });
  await expect.poll(async () => (await fixture.snapshot()).data.threads.find(t => t.id === 't')!.status).toBe('idle');
  const original = (await fixture.snapshot()).data.threads.find(t => t.id === 't')!;
  const session = await readFile(original.sessionFile!, 'utf8');
  await fixture.invoke({ op: 'ui.threadPatch', threadId: 't', patch: { draft: { text: 'UNSENT_ORIGINAL_DRAFT', attachments: [] } } });
  await writeFile(join(fixture.project, 'README.md'), 'DO_NOT_ROLL_BACK\n');
  await fixture.page.locator('.message.user').getByRole('button', { name: '编辑并重新发送', exact: true }).click();
  const dialog = fixture.page.getByRole('dialog', { name: '编辑并重新发送' });
  await expect(dialog).toContainText('工作区文件不会回滚');
  await dialog.getByLabel('消息内容', { exact: true }).fill('edited first question');
  await dialog.getByRole('button', { name: '创建分支草稿', exact: true }).click();
  await expect(dialog).toHaveCount(0);
  const revised = (await fixture.snapshot()).data.threads.find(t => t.revision?.parentThreadId === 't')!;
  expect(revised.items).toEqual([]);
  expect(revised.policy).toBe(original.policy);
  expect(revised.goal).toBeUndefined();
  expect((await fixture.snapshot()).data.ui.threads.t.draft?.text).toBe('UNSENT_ORIGINAL_DRAFT');
  expect(await readFile(original.sessionFile!, 'utf8')).toBe(session);
  expect(await readFile(join(fixture.project, 'README.md'), 'utf8')).toBe('DO_NOT_ROLL_BACK\n');
  await fixture.restart();
  expect((await fixture.snapshot()).data.ui.threads[revised.id].draft?.text).toBe('edited first question');
  await fixture.invoke({ op: 'thread.send', id: revised.id, text: 'edited first question', attachments: [], requestId: crypto.randomUUID() });
  await expect.poll(async () => (await fixture.snapshot()).data.threads.find(t => t.id === revised.id)!.status).toBe('idle');
  const call = JSON.stringify(fixture.calls.at(-1));
  expect(call).toContain('edited first question'); expect(call).not.toContain('original first question');
  expect(await readFile(original.sessionFile!, 'utf8')).toBe(session);
});

test('regeneration retains earlier history and copies attachments; duplicate requests cannot fork twice', async () => {
  await fixture.invoke({ op: 'thread.send', id: 't', text: 'EARLIER_HISTORY', attachments: [] });
  await expect.poll(async () => (await fixture.snapshot()).data.threads[0].status).toBe('idle');
  const files = await fixture.invoke({ op: 'attachment.add', threadId: 't', files: [{ name: 'context.txt', base64: Buffer.from('COPIED_ATTACHMENT').toString('base64') }] }) as string[];
  await fixture.invoke({ op: 'thread.send', id: 't', text: 'SECOND_QUESTION', attachments: files });
  await expect.poll(async () => (await fixture.snapshot()).data.threads[0].status).toBe('idle');
  const original = (await fixture.snapshot()).data.threads[0], answer = original.items.findLast(i => i.role === 'assistant')!;
  const request = { op: 'thread.revise' as const, threadId: 't', itemId: answer.id, kind: 'regenerate' as const, requestId: crypto.randomUUID() };
  const revision = await fixture.invoke(request) as { thread: Thread; payload: ComposerPayload };
  const duplicate = await fixture.invoke(request) as { thread: Thread };
  expect(duplicate.thread.id).toBe(revision.thread.id);
  expect(revision.thread.items.filter(i => i.role === 'user').map(i => i.input?.text)).toEqual(['EARLIER_HISTORY']);
  expect(revision.payload.text).toBe('SECOND_QUESTION');
  expect(revision.payload.attachments[0]).not.toBe(files[0]);
  expect(await readFile(revision.payload.attachments[0], 'utf8')).toBe('COPIED_ATTACHMENT');
  await fixture.invoke({ op: 'thread.send', id: revision.thread.id, ...revision.payload, requestId: request.requestId });
  await expect.poll(async () => (await fixture.snapshot()).data.threads.find(t => t.id === revision.thread.id)!.status).toBe('idle');
  expect(JSON.stringify(fixture.calls.at(-1))).toContain('EARLIER_HISTORY');
  expect(JSON.stringify(fixture.calls.at(-1))).toContain('COPIED_ATTACHMENT');
  expect((await fixture.snapshot()).data.threads.find(t => t.id === 't')!.items).toEqual(original.items);
});

test('message actions are keyboard reachable and running tasks reject branch operations', async () => {
  await fixture.invoke({ op: 'thread.send', id: 't', text: 'TO_COPY', attachments: [] });
  await expect.poll(async () => (await fixture.snapshot()).data.threads[0].status).toBe('idle');
  const user = fixture.page.locator('.message.user').first();
  await user.getByRole('button', { name: '复制消息', exact: true }).focus();
  await expect(user.locator('.message-actions')).toHaveCSS('opacity', '1');
  await fixture.page.keyboard.press('Enter');
  await expect(user.getByRole('button', { name: '已复制', exact: true })).toBeVisible();
  expect(await fixture.page.evaluate(() => navigator.clipboard.readText())).toBe('TO_COPY');
  const old = (await fixture.snapshot()).data.threads[0].items.find(i => i.role === 'user')!;
  fixture.setMode('hold'); await fixture.invoke({ op: 'thread.send', id: 't', text: 'CURRENTLY_RUNNING', attachments: [] });
  await expect.poll(() => fixture.calls.length).toBe(2);
  await expect(user.getByRole('button', { name: '编辑并重新发送', exact: true })).toBeDisabled();
  await expect(fixture.invoke({ op: 'thread.revise', threadId: 't', itemId: old.id, kind: 'edit', text: 'bad concurrent request', requestId: crypto.randomUUID() })).rejects.toThrow('请等待任务空闲再分叉');
  fixture.release();
  await expect.poll(async () => (await fixture.snapshot()).data.threads[0].status).toBe('idle');
});

test('only successful writes create historical edit previews that survive file changes and restart', async () => {
  fixture.requestTool('write', { path: 'report.txt', content: 'REAL_OUTPUT_CONTENT' });
  await fixture.invoke({ op: 'thread.send', id: 't', text: '写入产物', attachments: [] });
  await expect.poll(async () => (await fixture.snapshot()).data.threads[0].status).toBe('idle');
  const card = fixture.page.locator('.turn-changes').first();
  await expect(card).toHaveCount(1); await expect(card).toContainText('report.txt');
  await card.locator('.turn-change-row').click(); await expect(card.locator('.turn-written-content')).toHaveText('REAL_OUTPUT_CONTENT');
  await expect(fixture.page.locator('.turn-artifact-open')).toHaveCount(0);
  await writeFile(join(fixture.project, 'report.txt'), 'CHANGED_EXTERNALLY\n');
  fixture.requestTool('edit', { path: 'report.txt', oldText: 'CHANGED_EXTERNALLY', newText: 'EDITED_RESULT' });
  await fixture.invoke({ op: 'thread.send', id: 't', text: '编辑产物', attachments: [] });
  await expect.poll(async () => (await fixture.snapshot()).data.threads[0].status).toBe('idle');
  const edited = fixture.page.locator('.turn-changes').last();
  await expect(edited.locator('.turn-changes-heading .added')).toHaveText('+1');
  await expect(edited.locator('.turn-changes-heading .removed')).toHaveText('−1');
  await edited.locator('.turn-change-row').click();
  await expect(edited.locator('.diff .addition')).toContainText('EDITED_RESULT');
  await expect(edited.locator('.diff .deletion')).toContainText('CHANGED_EXTERNALLY');
  expect(await readFile(join(fixture.project, 'report.txt'), 'utf8')).toBe('EDITED_RESULT\n');
  await unlink(join(fixture.project, 'report.txt'));
  await fixture.restart();
  const restored = fixture.page.locator('.turn-changes');
  await restored.first().locator('.turn-change-row').click(); await expect(restored.first().locator('.turn-written-content')).toHaveText('REAL_OUTPUT_CONTENT');
  await restored.last().locator('.turn-change-row').click(); await expect(restored.last().locator('.diff .addition')).toContainText('EDITED_RESULT');
  fixture.requestTool('read', { path: 'README.md' });
  await fixture.invoke({ op: 'thread.send', id: 't', text: '读取不应成为产物', attachments: [] });
  await expect.poll(async () => (await fixture.snapshot()).data.threads[0].status).toBe('idle');
  await expect(fixture.page.locator('.turn').last().locator('.turn-changes')).toHaveCount(0);
});

test('sent image cards retain inspection rights after restart and inside a regenerated branch', async () => {
  const [path] = await fixture.invoke({ op: 'attachment.add', threadId: 't', files: [{ name: 'pixel.png', base64: 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j4YQAAAAASUVORK5CYII=' }] }) as string[];
  await fixture.invoke({ op: 'thread.send', id: 't', text: 'IMAGE_QUESTION', attachments: [path] });
  await expect.poll(async () => (await fixture.snapshot()).data.threads[0].status).toBe('idle');
  await fixture.page.getByRole('button', { name: '查看上下文 pixel.png', exact: true }).click();
  await expect(fixture.page.locator('.message-context-image')).toBeVisible();
  await fixture.restart();
  await expect(fixture.page.locator('.message-context-image')).toBeVisible();
  expect(await fixture.page.locator('.message-context-image').evaluate(image => (image as HTMLImageElement).naturalWidth)).toBe(1);
  await fixture.page.getByRole('button', { name: '重新生成回答', exact: true }).click();
  await fixture.page.getByRole('dialog', { name: '重新生成回答' }).getByRole('button', { name: '创建分支并发送', exact: true }).click();
  await expect.poll(() => fixture.calls.length).toBe(2);
  await expect.poll(async () => (await fixture.snapshot()).data.threads.find(t => t.revision?.parentThreadId === 't')?.status).toBe('idle');
  await expect(fixture.page.getByLabel('向 Pi 发送消息', { exact: true })).toHaveValue('');
  await expect.poll(async () => {
    const state = await fixture.snapshot();
    return state.data.ui.threads[state.data.ui.activeThreadId]?.draft?.text;
  }).toBe('');
  const state = await fixture.snapshot(), branch = state.data.threads.find(t => t.revision?.parentThreadId === 't')!;
  expect(state.data.ui.activeThreadId).toBe(branch.id);
  expect(state.data.ui.threads[branch.id].draft?.text).toBe('');
  await fixture.page.getByRole('button', { name: '查看上下文 pixel.png', exact: true }).click();
  await expect(fixture.page.locator('.message-context-image')).toBeVisible();
  const copied = branch.items.find(i => i.role === 'user')!.input!.parts.find(part => part.path)!.path!;
  expect(copied).not.toBe(path);
  expect(await readFile(copied)).toEqual(await readFile(path));
});

test('regeneration with a changed reference leaves the branch draft and shows its send failure', async () => {
  const detail = contextDetailSchema.parse(await fixture.invoke({ op: 'composer.contextDetail', threadId: 't', reference: { kind: 'file', id: 'README.md', label: 'README.md' } }));
  await fixture.invoke({ op: 'thread.send', id: 't', text: 'PRESERVE_ON_FAILED_SEND', attachments: [], context: [detail.reference] });
  await expect.poll(async () => (await fixture.snapshot()).data.threads[0].status).toBe('idle');
  await writeFile(join(fixture.project, 'README.md'), 'CHANGED_AFTER_ORIGINAL_SEND');
  await fixture.page.getByRole('button', { name: '重新生成回答', exact: true }).click();
  await fixture.page.getByRole('dialog', { name: '重新生成回答' }).getByRole('button', { name: '创建分支并发送', exact: true }).click();
  await expect(fixture.page.getByText('引用版本已变化，请查看详情并刷新引用', { exact: false })).toBeVisible();
  await expect(fixture.page.getByLabel('向 Pi 发送消息', { exact: true })).toHaveValue('PRESERVE_ON_FAILED_SEND');
  const state = await fixture.snapshot(), branch = state.data.threads.find(t => t.revision?.parentThreadId === 't')!;
  expect(branch.items).toEqual([]);
  expect(state.data.ui.threads[branch.id].contextReferences).toEqual([detail.reference]);
  expect(fixture.calls.length).toBe(1);
  await fixture.restart();
  expect((await fixture.snapshot()).data.ui.threads[branch.id].draft?.text).toBe('PRESERVE_ON_FAILED_SEND');
  await fixture.page.locator('.composer-reference-open').click();
  const dialog = fixture.page.getByRole('dialog', { name: '引用详情', exact: true });
  await dialog.getByRole('button', { name: '刷新引用', exact: true }).click();
  await expect(dialog.getByRole('alert')).toHaveCount(0);
  await dialog.getByRole('button', { name: '关闭', exact: true }).click();
  await fixture.page.getByRole('button', { name: '发送消息', exact: true }).click();
  await expect.poll(() => fixture.calls.length).toBe(2);
  await expect.poll(async () => (await fixture.snapshot()).data.threads.find(t => t.id === branch.id)!.status).toBe('idle');
  expect(JSON.stringify(fixture.calls.at(-1))).toContain('CHANGED_AFTER_ORIGINAL_SEND');
});
