import { taskAction } from './fixtures/task-actions.ts';
import { readFile, writeFile } from 'node:fs/promises';
import { createServer, type Server } from 'node:http';
import { join } from 'node:path';
import { expect, test } from '@playwright/test';
import type { Thread, FileContent } from '../../src/shared/contracts.ts';
import { acceptanceApp } from './fixtures/acceptance-app.ts';
import { startDevelopmentSource } from './fixtures/development-source.ts';

let development: Awaited<ReturnType<typeof startDevelopmentSource>>;
let fixture: Awaited<ReturnType<typeof acceptanceApp>>;
test.beforeAll(async () => { development = await startDevelopmentSource(); });
test.afterAll(async () => { await development?.server.close(); });
test.beforeEach(async () => { fixture = await acceptanceApp(development.url); });
test.afterEach(async () => { const errors = [...fixture.errors]; await fixture.close(); expect(errors).toEqual([]); });

async function idle() {
  await expect.poll(async () => (await fixture.snapshot()).data.threads.find(thread => thread.id === 't')?.status).toBe('idle');
}
async function send(text: string) {
  const count = fixture.calls.length;
  await fixture.invoke({ op: 'thread.send', id: 't', text, attachments: [] });
  await expect.poll(() => fixture.calls.length).toBeGreaterThan(count);
  await idle();
}

test('workbench drafts, queue withdrawal, per-turn plans and terminal profiles survive restart', async () => {
  const page = fixture.page;
  await fixture.invoke({ op: 'ui.threadPatch', threadId: 't', patch: { reviewTab: 'summary' } });
  const input = page.getByLabel('向 Pi 发送消息');
  await input.fill('第一份中文草稿');
  const attachment = join(fixture.project, '草稿附件.txt');
  await writeFile(attachment, 'DRAFT_ATTACHMENT');
  await fixture.app.evaluate(({ dialog }, path) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [path] }); }, attachment);
  await page.getByLabel('添加上下文与操作', { exact: true }).click();
  await page.getByRole('menuitem', { name: '添加附件', exact: true }).click();
  await expect.poll(async () => (await fixture.snapshot()).data.ui.threads.t.draft?.attachments.length).toBe(1);
  const copied = (await fixture.snapshot()).data.ui.threads.t.draft!.attachments[0];
  expect(copied).not.toBe(attachment);
  const second = await fixture.invoke({ op: 'thread.create', projectId: 'p', worktree: false }) as Thread;
  await page.locator('.thread-main').filter({ hasText: second.title }).click();
  await input.fill('第二份草稿');
  await page.locator('.thread-main').filter({ hasText: '验收任务' }).click();
  await expect(input).toHaveValue('第一份中文草稿');
  await expect(page.locator('.attachment-name')).toHaveCount(1);
  await fixture.restart();
  await expect(fixture.page.getByLabel('向 Pi 发送消息')).toHaveValue('第一份中文草稿');
  expect(await readFile(copied, 'utf8')).toBe('DRAFT_ATTACHMENT');
  expect(fixture.calls).toHaveLength(0);
  fixture.setMode('hold');
  await fixture.invoke({ op: 'thread.send', id: 't', text: '开始长任务', attachments: [] });
  await expect.poll(() => fixture.calls.length).toBe(1);
  await fixture.invoke({ op: 'thread.send', id: 't', text: '队列补充', attachments: [copied], queue: 'followUp' });
  await expect(fixture.page.getByLabel('排队消息', { exact: true })).toContainText('队列补充');
  await fixture.page.getByRole('button', { name: '全部撤回至草稿' }).click();
  await expect.poll(async () => (await fixture.snapshot()).data.threads.find(thread => thread.id === 't')?.queue?.length).toBe(0);
  await expect(fixture.page.getByLabel('向 Pi 发送消息')).toHaveValue(/第一份中文草稿.*队列补充/s);
  expect((await fixture.snapshot()).data.ui.threads.t.draft!.attachments).toContain(copied);
  await fixture.invoke({ op: 'thread.stop', id: 't' });
  fixture.release();
  await idle();
  fixture.requestTool('update_plan', { steps: [{ text: '读取项目', status: 'completed' }, { text: '补全功能', status: 'in_progress' }] });
  await send('制定本轮计划');
  const plan = fixture.page.locator('[data-disclosure^="plan:"]');
  await expect(plan).toHaveCount(1);
  await expect(plan.getByRole('button')).toHaveAttribute('aria-expanded', 'false');
  await plan.getByRole('button').click();
  await expect(plan).toContainText('读取项目');
  await send('下一轮不更新计划');
  await expect(plan).toHaveCount(1);
  const terminal = await fixture.invoke({ op: 'terminal.open', threadId: 't' }) as { id: string };
  await fixture.invoke({ op: 'terminal.rename', id: terminal.id, title: '验证终端' });
  await fixture.invoke({ op: 'ui.threadPatch', threadId: 't', patch: { terminalOpen: true } });
  await fixture.restart();
  await expect(fixture.page.locator('[data-disclosure^="plan:"]').getByRole('button')).toHaveAttribute('aria-expanded', 'true');
  expect((await fixture.snapshot()).terminals).toHaveLength(0);
  await expect(fixture.page.getByRole('button', { name: /重新启动 验证终端/ })).toBeVisible();
  await fixture.page.getByRole('button', { name: /重新启动 验证终端/ }).click();
  await expect.poll(async () => (await fixture.snapshot()).terminals.length).toBe(1);
  expect((await fixture.snapshot()).terminals[0].title).toBe('验证终端');
});

test('workbench context menus, recycle bin, export and message fork work without task tabs', async () => {
  await send('会话操作验收');
  const page = fixture.page;
  const row = page.locator('.thread-row').filter({ hasText: '验收任务' });
  await row.click({ button: 'right' });
  await page.getByRole('menuitem', { name: '重命名', exact: true }).click();
  await page.getByLabel('任务名称', { exact: true }).fill('工作台验收');
  await page.getByRole('dialog').getByRole('button', { name: '保存', exact: true }).click();
  const renamed = page.locator('.thread-row').filter({ hasText: '工作台验收' });
  await renamed.getByLabel('任务更多操作', { exact: true }).click();
  await page.getByRole('menuitem', { name: '置顶', exact: true }).click();
  await expect.poll(async () => (await fixture.snapshot()).data.threads[0].pinned).toBe(true);
  await expect(page.getByRole('tablist', { name: '任务标签', exact: true })).toHaveCount(0);
  expect((await fixture.snapshot()).data.threads).toHaveLength(1);
  await expect(renamed).toHaveClass(/selected/);
  const output = join(fixture.storage, 'export.md');
  await fixture.app.evaluate(({ dialog }, path) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath: path }); }, output);
  await renamed.getByLabel('任务更多操作', { exact: true }).click();
  await page.getByRole('menuitem', { name: '导出 Markdown', exact: true }).click();
  await expect.poll(async () => readFile(output, 'utf8').catch(() => '')).toContain('会话操作验收');
  const original = (await fixture.snapshot()).data.threads[0];
  const entry = original.items.find(item => item.role === 'user')!.entryId!;
  const fork = await fixture.invoke({ op: 'thread.fork', id: 't', entryId: entry }) as Thread;
  expect(fork.id).not.toBe('t');
  expect(fork.sessionFile).not.toBe(original.sessionFile);
  expect((await fixture.snapshot()).data.threads.find(thread => thread.id === 't')?.sessionFile).toBe(original.sessionFile);
  await fixture.invoke({ op: 'thread.update', id: fork.id, deletedAt: Date.now() });
  expect((await fixture.snapshot()).data.threads.find(thread => thread.id === fork.id)?.deletedAt).toBeTruthy();
  await fixture.invoke({ op: 'thread.update', id: fork.id, deletedAt: null });
  expect((await fixture.snapshot()).data.threads.find(thread => thread.id === fork.id)?.deletedAt).toBeNull();
  await fixture.restart();
  expect((await fixture.snapshot()).data.threads).toHaveLength(2);
  expect(await readFile(join(fixture.project, 'README.md'), 'utf8')).toContain('Acceptance');
  const attachment = join(fixture.project, 'purge.txt'); await writeFile(attachment, 'SOURCE_ATTACHMENT');
  await fixture.app.evaluate(({ dialog }, path) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [path] }); }, attachment);
  const picked = await fixture.invoke({ op: 'attachment.pick', threadId: fork.id }) as string[];
  await fixture.invoke({ op: 'thread.update', id: fork.id, deletedAt: Date.now() });
  await fixture.app.evaluate(({ dialog }) => { dialog.showMessageBox = async () => ({ response: 0, checkboxChecked: false }); });
  await fixture.invoke({ op: 'thread.purge', id: fork.id });
  expect((await fixture.snapshot()).data.threads).toHaveLength(2);
  expect(await readFile(picked[0], 'utf8')).toBe('SOURCE_ATTACHMENT');
  await fixture.app.evaluate(({ dialog }) => { dialog.showMessageBox = async () => ({ response: 1, checkboxChecked: false }); });
  await fixture.invoke({ op: 'thread.purge', id: fork.id });
  await expect(readFile(fork.sessionFile!)).rejects.toMatchObject({ code: 'ENOENT' });
  await expect(readFile(picked[0])).rejects.toMatchObject({ code: 'ENOENT' });
  expect(await readFile(original.sessionFile!, 'utf8')).toContain('会话操作验收');
  expect(await readFile(attachment, 'utf8')).toBe('SOURCE_ATTACHMENT');
  expect(JSON.parse(await readFile(join(fixture.storage, 'desktop.json.bak'), 'utf8')).threads).toHaveLength(1);
  await fixture.restart();
  expect((await fixture.snapshot()).data.threads.map(thread => thread.id)).toEqual(['t']);
});

test('workbench reading anchors flush on rapid task switches and survive restart without following new content', async () => {
  for (let index = 0; index < 8; index++) await send('阅读位置第 ' + index + ' 轮\n' + Array.from({ length: 35 }, (_, line) => '正文行 ' + line).join('\n'));
  const other = await fixture.invoke({ op: 'thread.create', projectId: 'p', worktree: false }) as Thread;
  const expected = await fixture.page.locator('.thread-main').filter({ hasText: other.title }).evaluate(node => {
    const timeline = document.querySelector<HTMLElement>('.timeline')!;
    const target = timeline.querySelectorAll<HTMLElement>('[data-turn-key]')[1];
    timeline.scrollTop += target.getBoundingClientRect().top - timeline.getBoundingClientRect().top + 25;
    timeline.dispatchEvent(new Event('scroll'));
    const anchor = { key: target.dataset.turnKey!, offset: target.getBoundingClientRect().top - timeline.getBoundingClientRect().top, remaining: timeline.scrollHeight - timeline.scrollTop - timeline.clientHeight };
    (node as HTMLElement).click();
    return anchor;
  });
  expect(expected.remaining).toBeGreaterThan(100);
  await expect.poll(async () => (await fixture.snapshot()).data.ui.threads.t.scroll?.follow).toBe(false);
  expect((await fixture.snapshot()).data.ui.threads.t.scroll?.itemId).toBe(expected.key);
  await fixture.page.locator('.thread-main').filter({ hasText: '验收任务' }).click();
  const offset = () => fixture.page.locator('.timeline').evaluate((node, key) => {
    const anchor = [...node.querySelectorAll<HTMLElement>('[data-turn-key]')].find(item => item.dataset.turnKey === key)!;
    return anchor.getBoundingClientRect().top - node.getBoundingClientRect().top;
  }, expected.key);
  await expect.poll(async () => Math.abs(await offset() - expected.offset)).toBeLessThanOrEqual(.5);
  await fixture.restart();
  await expect.poll(async () => Math.abs(await offset() - expected.offset)).toBeLessThanOrEqual(.5);
  await fixture.page.getByRole('button', { name: '回到最新消息', exact: true }).click();
  await expect.poll(async () => (await fixture.snapshot()).data.ui.threads.t.scroll?.follow).toBe(true);
  await fixture.restart();
  await expect.poll(() => fixture.page.locator('.timeline').evaluate(node => node.scrollHeight - node.scrollTop - node.clientHeight)).toBeLessThanOrEqual(1);
  expect(fixture.calls).toHaveLength(8);
});

test('workbench editor preserves stale buffers, confirms unsaved close and stages only chosen files', async () => {
  const page = fixture.page;
  if (!await page.locator('.review-pane').isVisible()) await taskAction(page, '查看变更');
  await page.getByRole('button', { name: '新标签', exact: true }).click();
  await page.locator('.tool-launcher').getByRole('button', { name: '文件', exact: true }).click();
  await page.getByRole('treeitem', { name: /README.md/ }).click();
  const editor = page.getByLabel('文件内容 README.md');
  await expect(editor).toContainText('Acceptance');
  await editor.fill('# Edited\n');
  await page.getByLabel('视图菜单').click();
  await page.getByRole('menuitem', { name: '任务摘要', exact: true }).click();
  await writeFile(join(fixture.project, 'README.md'), '# Outside\n');
  await taskAction(page, '查看变更');
  await page.getByRole('tab', { name: /^README\.md/ }).click();
  await expect(editor).toHaveValue('# Edited\n');
  await page.getByRole('button', { name: '保存 *', exact: true }).click();
  await expect(page.locator('.files-workbench').getByRole('alert')).toContainText(/修改|版本/);
  expect(await readFile(join(fixture.project, 'README.md'), 'utf8')).toBe('# Outside\n');
  await fixture.app.evaluate(({ dialog }) => { dialog.showMessageBoxSync = () => 0; });
  await fixture.invoke({ op: 'window', action: 'close' });
  await expect(editor).toBeVisible();
  await page.getByRole('button', { name: '重新加载', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: '放弃修改', exact: true }).click();
  await expect(editor).toHaveValue('# Outside\n');
  await editor.fill('# Saved\n');
  await page.getByRole('button', { name: '保存 *', exact: true }).click();
  await expect(page.locator('.files-workbench').getByRole('alert')).toHaveCount(0);
  await expect.poll(() => readFile(join(fixture.project, 'README.md'), 'utf8')).toBe('# Saved\n');
  await writeFile(join(fixture.project, 'unrelated.txt'), 'keep\n');
  await page.getByRole('tab', { name: /^变更/ }).click();
  await page.getByLabel('刷新 Git').click();
  await page.getByLabel('暂存 README.md', { exact: true }).click();
  await page.getByRole('button', { name: 'Git 操作', exact: true }).click();
  await page.getByLabel('提交信息').fill('workbench acceptance');
  await page.getByRole('button', { name: '提交所选暂存文件', exact: true }).click();
  await expect.poll(async () => (await fixture.invoke({ op: 'git.status', threadId: 't' }) as { files: { path: string }[] }).files.map(item => item.path)).toEqual(['unrelated.txt']);
  await page.getByText('提交历史', { exact: true }).click();
  await page.getByRole('button', { name: /workbench acceptance/ }).click();
  await expect(page.locator('.diff').last()).toContainText('+# Saved');
  const baseline = await fixture.invoke({ op: 'file.read', threadId: 't', path: 'README.md' }) as FileContent;
  expect(baseline.writable).toBe(true);
  await fixture.restart();
  expect((await fixture.snapshot()).data.ui.threads.t.openFiles).toContain('README.md');
});

test('workbench calendar editing keeps timezone and notification preferences across restart', async () => {
  const page = fixture.page;
  await page.getByRole('button', { name: '自动化', exact: true }).click();
  await page.getByRole('button', { name: '新建自动化', exact: true }).click();
  await page.getByLabel('名称', { exact: true }).fill('每月检查');
  await page.getByLabel('任务描述', { exact: true }).fill('检查本地项目');
  await page.getByLabel('计划类型').click();
  await page.locator('.menu-item[data-value="monthly"]').click();
  await page.getByLabel('时间', { exact: true }).fill('02:30');
  await page.getByLabel(/^时区/).fill('America/New_York');
  await page.getByLabel('日期', { exact: true }).fill('31');
  await page.getByRole('button', { name: '创建自动化', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('已创建 每月检查');
  const job = (await fixture.snapshot()).data.automations[0];
  expect(job.schedule).toMatchObject({ kind: 'monthly', time: '02:30', timezone: 'America/New_York', monthday: 31 });
  await page.getByRole('button', { name: '编辑', exact: true }).click();
  await page.getByLabel('计划类型').click();
  await page.locator('.menu-item[data-value="weekly"]').click();
  await page.getByLabel('星期', { exact: true }).click();
  await page.locator('.menu-item[data-value="5"]').click();
  await page.getByRole('button', { name: '保存自动化', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('已保存 每月检查');
  const settings = (await fixture.snapshot()).data.settings;
  await fixture.invoke({ op: 'settings.save', settings: { ...settings, notifications: false } });
  await fixture.restart();
  const restored = await fixture.snapshot();
  expect(restored.data.automations).toHaveLength(1);
  expect(restored.data.automations[0].schedule).toMatchObject({ kind: 'weekly', weekday: 5, timezone: 'America/New_York' });
  expect(restored.data.settings.notifications).toBe(false);
  expect(fixture.calls).toHaveLength(0);
});

test('workbench browser keeps cookies, native tabs and downloads separate from desktop IPC', async () => {
  const servers: Server[] = [];
  const startSite = async (title: string) => {
    const server = createServer((request, response) => {
      if (request.url === '/download') { response.writeHead(200, { 'Content-Disposition': 'attachment; filename="workbench.txt"', 'Content-Type': 'text/plain' }); response.end('DOWNLOAD_ACCEPTANCE'); return; }
      if (request.url === '/login') response.setHeader('Set-Cookie', 'pi_acceptance=logged-in; Path=/; Max-Age=86400; SameSite=Lax');
      response.setHeader('Content-Type', 'text/html; charset=utf-8');
      response.end('<title>' + title + '</title><p>browser needle needle</p><a id="next" href="/next">next</a><button id="popup" onclick="window.open(\'/login\',\'login\')">login</button><input id="upload" type="file"><a id="download" href="/download">download</a>');
    });
    await new Promise<void>(resolve => server.listen(0, '127.0.0.1', resolve));
    servers.push(server);
    const address = server.address();
    if (!address || typeof address === 'string') throw new Error('Missing local browser server');
    return 'http://127.0.0.1:' + address.port;
  };
  try {
    const first = await startSite('站点一');
    const second = await startSite('站点二');
    const page = fixture.page;
    await page.getByLabel('视图菜单').click();
    await page.getByRole('menuitem', { name: '切换浏览器预览', exact: true }).click();
    await page.getByLabel('预览地址').fill(first + '/login');
    await page.getByRole('button', { name: '打开', exact: true }).click();
    await expect(page.getByRole('tab', { name: '站点一', exact: true })).toBeVisible();
    const contentId = await fixture.app.evaluate(({ webContents }, url) => webContents.getAllWebContents().find(item => item.getURL() === url)?.id, first + '/login');
    expect(contentId).toBeTruthy();
    const readPage = (expression: string) => fixture.app.evaluate(({ webContents }, input) => webContents.fromId(input.id!)!.executeJavaScript(input.expression), { id: contentId, expression });
    expect(await readPage('[typeof window.desktop,typeof require,typeof process]')).toEqual(['undefined', 'undefined', 'undefined']);
    await expect.poll(() => readPage('document.cookie')).toContain('pi_acceptance=logged-in');
    await page.getByLabel('浏览器操作', { exact: true }).click();
    await page.getByRole('menuitem', { name: '网页内查找', exact: true }).click();
    await page.getByLabel('网页内查找').fill('needle');
    await expect(page.getByRole('search', { name: '网页查找' }).getByRole('status')).toHaveText('第 1/2 处');
    await page.getByLabel('浏览器操作', { exact: true }).click();
    await page.getByRole('menuitem', { name: '放大', exact: true }).click();
    await expect(page.getByLabel('网页缩放')).toHaveText('110%');
    await page.getByRole('button', { name: '新标签', exact: true }).click();
    await expect(page.getByRole('tab', { name: '新标签', exact: true })).toHaveAttribute('aria-selected', 'true');
    await page.getByLabel('预览地址').fill(second);
    await page.getByRole('button', { name: '打开', exact: true }).click();
    await expect(page.getByRole('tab', { name: '站点二', exact: true })).toBeVisible();
    await page.getByRole('tab', { name: '站点一', exact: true }).click();
    await expect.poll(() => readPage('document.cookie')).toContain('pi_acceptance=logged-in');
    const download = join(fixture.storage, 'download.txt');
    await fixture.app.evaluate(({ session }, path) => { session.fromPartition('persist:pi-browser').on('will-download', (_event, item) => item.setSavePath(path)); }, download);
    await readPage('document.querySelector("#download").click()');
    await expect.poll(() => readFile(download, 'utf8').catch(() => '')).toBe('DOWNLOAD_ACCEPTANCE');
    await expect(page.getByRole('button', { name: '打开所在目录', exact: true })).toBeVisible();
    const upload = join(fixture.project, 'upload.txt');
    await writeFile(upload, 'UPLOAD_ACCEPTANCE');
    await fixture.app.evaluate(async ({ webContents }, input) => {
      const debuggerApi = webContents.fromId(input.id!)!.debugger;
      debuggerApi.attach('1.3');
      try {
        const doc = await debuggerApi.sendCommand('DOM.getDocument');
        const node = await debuggerApi.sendCommand('DOM.querySelector', { nodeId: doc.root.nodeId, selector: '#upload' });
        await debuggerApi.sendCommand('DOM.setFileInputFiles', { nodeId: node.nodeId, files: [input.path] });
      } finally { debuggerApi.detach(); }
    }, { id: contentId, path: upload });
    expect(await readPage('document.querySelector("#upload").files[0].name')).toBe('upload.txt');
    await fixture.app.evaluate(async ({ webContents }, id) => {
      const wc = webContents.fromId(id!)!;
      const bounds = await wc.executeJavaScript('(()=>{const r=document.querySelector("#popup").getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()');
      wc.sendInputEvent({ type: 'mouseDown', x: Math.round(bounds.x), y: Math.round(bounds.y), button: 'left', clickCount: 1 });
      wc.sendInputEvent({ type: 'mouseUp', x: Math.round(bounds.x), y: Math.round(bounds.y), button: 'left', clickCount: 1 });
    }, contentId);
    await expect.poll(async () => (await fixture.snapshot()).data.ui.threads.t.browserTabs?.length).toBe(3);
    await expect(page.locator('.browser-tabs [role=tab]')).toHaveCount(3);
    await fixture.app.evaluate(async ({ webContents }, input) => {
      const popup = webContents.getAllWebContents().find(item => item.id !== input.parent && item.getURL() === input.url);
      if (!popup) throw new Error('Login popup did not load');
      await popup.executeJavaScript('window.close()').catch(() => {});
    }, { parent: contentId, url: first + '/login' });
    await expect.poll(async () => (await fixture.snapshot()).data.ui.threads.t.browserTabs?.length).toBe(2);
    await page.getByLabel('浏览器操作', { exact: true }).click();
    await page.getByRole('menuitem', { name: '恢复关闭标签', exact: true }).click();
    await expect(page.locator('.browser-tabs [role=tab]')).toHaveCount(3);
    await page.locator('.workspace-tabs [role=tab][aria-selected=true]').click({ button: 'middle' });
    await expect.poll(async () => (await fixture.snapshot()).data.ui.threads.t.browserTabs?.length).toBe(2);
    await page.getByLabel('浏览器操作', { exact: true }).click();
    await page.getByRole('menuitem', { name: '恢复关闭标签', exact: true }).click();
    await expect.poll(async () => (await fixture.snapshot()).data.ui.threads.t.browserTabs?.length).toBe(3);
    const other = await fixture.invoke({ op: 'thread.create', projectId: 'p', worktree: false }) as Thread;
    await page.locator('.thread-main').filter({ hasText: other.title }).click();
    await page.getByLabel('视图菜单').click();
    await page.getByRole('menuitem', { name: '切换浏览器预览', exact: true }).click();
    await page.getByLabel('预览地址').fill(first + '/shared');
    await page.getByRole('button', { name: '打开', exact: true }).click();
    await expect(page.getByRole('tab', { name: '站点一', exact: true })).toBeVisible();
    expect(await fixture.app.evaluate(async ({ webContents }, url) => webContents.getAllWebContents().find(item => item.getURL() === url)!.executeJavaScript('document.cookie'), first + '/shared')).toContain('pi_acceptance=logged-in');
    await page.locator('.thread-main').filter({ hasText: '验收任务' }).click();
    await expect(page.locator('.browser-tabs [role=tab]')).toHaveCount(3);
    const visibleViews = () => fixture.app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].contentView.children.filter(view => view.getVisible()).length);
    await expect.poll(visibleViews).toBe(1);
    const taskMenu = page.locator('.thread-row').filter({ hasText: '验收任务' }).getByLabel('任务更多操作', { exact: true });
    // Activating the trigger from the keyboard avoids the row tooltip that covers it on hover.
    await taskMenu.focus();
    await page.keyboard.press('Enter');
    await expect.poll(visibleViews).toBe(0);
    await page.keyboard.press('Escape');
    await expect(page.locator('.thread-row').filter({ hasText: '验收任务' }).getByLabel('任务更多操作', { exact: true })).toBeFocused();
    await expect.poll(visibleViews).toBe(1);
    await page.getByLabel('隐藏浏览器').click();
    expect(await fixture.app.evaluate(({ webContents }, id) => !!webContents.fromId(id!), contentId)).toBe(true);
    await fixture.restart();
    expect((await fixture.snapshot()).data.ui.threads.t.browserTabs).toHaveLength(3);
    expect(await fixture.app.evaluate(({ webContents }, url) => webContents.getAllWebContents().filter(item => item.getURL().startsWith(url)).length, first)).toBe(0);
    await fixture.page.getByLabel('视图菜单').click();
    await fixture.page.getByRole('menuitem', { name: '切换浏览器预览', exact: true }).click();
    await expect.poll(() => fixture.app.evaluate(({ session }, url) => session.fromPartition('persist:pi-browser').cookies.get({ url }), first)).toEqual(expect.arrayContaining([expect.objectContaining({ name: 'pi_acceptance', value: 'logged-in' })]));
    await expect(fixture.invoke({ op: 'browser.open', threadId: 't', tabId: 'invalid', url: 'file:///C:/Windows/win.ini' })).rejects.toThrow();
  } finally { for (const server of servers) { server.closeAllConnections(); await new Promise<void>(resolve => server.close(() => resolve())); } }
});

test('expanded skill queue withdrawal restores the original command and attachments', async () => {
  await fixture.invoke({ op: 'resource.create', name: '队列技能', content: '---\nname: queued-skill\ndescription: Queue test\n---\n\nEXPANDED_SKILL_CONTENT' });
  const attachment = join(fixture.project, 'queue.txt');
  await writeFile(attachment, 'QUEUED_ATTACHMENT');
  await fixture.app.evaluate(({ dialog }, path) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [path] }); }, attachment);
  const picked = await fixture.invoke({ op: 'attachment.pick', threadId: 't' }) as string[];
  fixture.setMode('hold');
  await fixture.invoke({ op: 'thread.send', id: 't', text: '长任务', attachments: [] });
  await expect.poll(() => fixture.calls.length).toBe(1);
  await fixture.invoke({ op: 'thread.send', id: 't', text: '/skill:queued-skill', attachments: picked, queue: 'followUp' });
  await expect.poll(async () => (await fixture.snapshot()).data.threads[0].queue?.[0]?.text).toBe('/skill:queued-skill');
  await fixture.page.getByLabel('向 Pi 发送消息').fill('刚输入的草稿');
  await fixture.page.getByRole('button', { name: '全部撤回至草稿' }).click();
  await expect(fixture.page.getByLabel('向 Pi 发送消息')).toHaveValue('刚输入的草稿\n\n/skill:queued-skill');
  expect((await fixture.snapshot()).data.ui.threads.t.draft?.attachments).toEqual(picked);
  await fixture.invoke({ op: 'thread.stop', id: 't' });
  fixture.release(); await idle();
  expect(fixture.calls).toHaveLength(1);
});
