import { defineConfig } from '@playwright/test';

export default defineConfig({
  testDir: './test/e2e',
  testMatch: [
    'composer.spec.ts',
    'conversation-ui.spec.ts',
    'turn-changes.spec.ts',
    'composer-enhancements.nonvisual.spec.ts',
    'message-experience.nonvisual.spec.ts',
    'message-rendering.nonvisual.spec.ts',
    'composer-recovery.spec.ts',
    'settings.spec.ts',
    'form-navigation.spec.ts',
    'localization.nonvisual.spec.ts',
    'model-settings.nonvisual.spec.ts',
    'provider-oauth-ui.spec.ts',
    'provider-oauth.nonvisual.spec.ts',
    'settings-persistence.nonvisual.spec.ts',
    'sidebar.spec.ts',
    'primitives.spec.ts',
    'panels.spec.ts',
    'git-panel.spec.ts',
    'git.nonvisual.spec.ts',
    'git-cancel-retry.nonvisual.spec.ts',
    'git-background.nonvisual.spec.ts',
    'review.nonvisual.spec.ts',
    'review-recovery.spec.ts',
    'git-history.nonvisual.spec.ts',
    'project-actions.nonvisual.spec.ts',
    'project-action-recovery.nonvisual.spec.ts',
    'project-action-recovery.spec.ts',
    'worktree-lifecycle.nonvisual.spec.ts',
    'worktree-controls.spec.ts',
    'worktree-cancellation.nonvisual.spec.ts',
    'worktree-migration-recovery.nonvisual.spec.ts',
    'worktree-interruption.nonvisual.spec.ts',
    'worktree-restore.nonvisual.spec.ts',
    'worktree-owner-recovery.nonvisual.spec.ts',
    'worktree-creation-interruption.nonvisual.spec.ts',
    'worktree-restore-files.nonvisual.spec.ts',
    'worktree-reclamation.nonvisual.spec.ts',
    'management.spec.ts',
    'management.nonvisual.spec.ts',
    'summary.spec.ts',
    'summary.nonvisual.spec.ts',
    'reference.spec.ts',
    'satang.spec.ts',
    'satang-workspace.spec.ts',
    'reference-states.spec.ts',
    'surfaces.spec.ts',
    'desktop.nonvisual.spec.ts',
    'permissions.nonvisual.spec.ts',
    'approval-review.nonvisual.spec.ts',
    'acceptance.spec.ts',
    'skills.nonvisual.spec.ts',
    'plugins.nonvisual.spec.ts',
    'plugin-management.spec.ts',
    'resources.spec.ts',
    'mcp-settings.spec.ts',
    'mcp.nonvisual.spec.ts',
    'mcp-test-cancellation.nonvisual.spec.ts',
    'mcp-reconnect.nonvisual.spec.ts',
    'runtime-startup.nonvisual.spec.ts',
    'mcp-oauth.nonvisual.spec.ts',
    'mcp-policies.nonvisual.spec.ts',
    'tool-results.nonvisual.spec.ts',
    'activity.spec.ts',
    'conversation.nonvisual.spec.ts',
    'workbench.nonvisual.spec.ts',
    'search.nonvisual.spec.ts',
    'message-links.nonvisual.spec.ts',
    'file-navigation.nonvisual.spec.ts',
    'file-editor.spec.ts',
    'file-editor.nonvisual.spec.ts',
    'terminal.nonvisual.spec.ts',
    'terminal-recovery.spec.ts',
    'browser.nonvisual.spec.ts',
    'browser-tools.nonvisual.spec.ts',
    'browser-bridge.nonvisual.spec.ts',
    'browser-bridge.spec.ts',
    'browser-annotations.nonvisual.spec.ts',
    'browser-annotations-recovery.spec.ts',
    'browser-history.nonvisual.spec.ts',
    'browser-history-recovery.spec.ts',
    'browser-sites-recovery.spec.ts',
    'artifacts.nonvisual.spec.ts',
    'artifact-recovery.spec.ts',
    'goals.nonvisual.spec.ts',
    'goal-recovery.spec.ts',
    'automation-queue.nonvisual.spec.ts',
    'memories.nonvisual.spec.ts',
    'memory-settings.spec.ts',
    'subtasks.nonvisual.spec.ts',
    'harness-tools.nonvisual.spec.ts',
    'desktop-tools.nonvisual.spec.ts',
    'ask-user.nonvisual.spec.ts',
    'harness-terminal.nonvisual.spec.ts',
    'harness-operations.nonvisual.spec.ts',
    'subtask-recovery.spec.ts',
    'sidechat-recovery.nonvisual.spec.ts',
    'sidechat-recovery.spec.ts',
    'window-recovery.nonvisual.spec.ts',
    'chat-recovery.nonvisual.spec.ts',
    'task-creation.nonvisual.spec.ts',
    'chat-recovery.spec.ts',
    'voice.nonvisual.spec.ts',
    'data-recovery.nonvisual.spec.ts',
    'final-ui.nonvisual.spec.ts',
  ],
  timeout: 120000,
  expect: { timeout: 15000 },
  workers: 1,
  reporter: [['list'], ['json', { outputFile: '../../.artifacts/desktop-nonvisual-results.json' }]],
  outputDir: '../../.artifacts/desktop-nonvisual',
  use: { screenshot: 'off', video: 'off', trace: 'off' },
});
